// 파일명: web-games/vibe-maker/workbench.js
// 역할: 브라우저 바이브 개발 작업실의 프로젝트 분석/수정/백업/비교 실행기
// 규칙: 기존 파일을 먼저 읽고, 저장 전 스냅샷 생성, 모바일 우선

import { createVibeBuildPlan } from '../../assets/vibe-build-plan.js';

const STORAGE_KEY='jaewoon-vibe-workbench';
const clean=v=>String(v??'').trim();
const loadState=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return{}}};
const saveState=s=>localStorage.setItem(STORAGE_KEY,JSON.stringify(s));
const textList=v=>Array.isArray(v)?v.filter(Boolean).map(clean):[];
const QUALITY=[['visual',['그래픽','에셋','배경','스타일','비주얼']],['animation',['애니','모션','움직임','프레임']],['vfx',['이펙트','VFX','타격','폭발','연출','파티클']],['audio',['사운드','소리','음악','BGM','효과음']],['gameplay',['재미','게임성','전투','보상','웨이브','밸런스','플레이']],['ui',['UI','UX','배치','버튼','직관','터치','조작','조이스틱']],['performance',['성능','느려','로딩','프레임','메모리','최적화']],['multiplayer',['멀티','협동','AI','NPC','동기화','온라인']]];
const detectQuality=r=>QUALITY.filter(([,w])=>w.some(x=>clean(r).toLowerCase().includes(String(x).toLowerCase()))).map(([k])=>k);
const SCORE={visual:['asset','sprite','texture','background','character','enemy','boss','ui','theme','style'],animation:['animation','anim','sprite','character','enemy','player'],vfx:['particle','effect','vfx','projectile','combat','main'],audio:['audio','sound','music','bgm','sfx','main'],gameplay:['main','game','combat','wave','enemy','player'],ui:['ui','hud','menu','main','scene','tscn','html','css'],performance:['main','game','project'],multiplayer:['multi','network','peer','ai','npc','main']};
const EXT_SCORE={godot:{'.gd':5,'.tscn':5,'.tres':3,'.cfg':2},web:{'.js':5,'.mjs':5,'.html':5,'.css':4,'.json':2}};
const PROTECTED=[['체력',/\b(?:hp|health|max_health|max_hp)\b|체력/i],['공격력',/\b(?:damage|attack_damage|atk)\b|공격력|데미지/i],['웨이브',/\bwave(?:s|_count|_max)?\b|웨이브/i],['보상',/\b(?:reward|gold|coin|drop_rate)\b|보상|드랍률/i],['저장',/\b(?:save_key|storage_key|localstorage|save_version)\b|저장\s*키|세이브/i]];
const PROTECTED_INTENT={체력:/체력|\bhp\b|health|max[_\s-]?hp/i,공격력:/공격력|데미지|\bdamage\b|attack[_\s-]?damage|\batk\b/i,웨이브:/웨이브|\bwave(?:s)?\b/i,보상:/보상|골드|코인|드랍|\bdrop(?:_rate)?\b|\breward\b|\bgold\b|\bcoin\b/i,저장:/마이그레이션|저장\s*(?:구조|키)|세이브\s*(?:구조|키)|save[_\s-]?(?:key|version)|storage[_\s-]?key/i};
const ext=p=>{const i=p.lastIndexOf('.');return i<0?'':p.slice(i).toLowerCase()};
export const diffVibeText=(a,b)=>{const x=String(a).split(/\r?\n/),y=String(b).split(/\r?\n/),out=[];for(let i=0;i<Math.max(x.length,y.length);i++)if(x[i]!==y[i])out.push({line:i+1,before:x[i]??'',after:y[i]??''});return out};
export const findProtectedVibeChanges=(current,next)=>{const lines=diffVibeText(current,next),hits=[];for(const[name,re]of PROTECTED)if(lines.some(x=>re.test(`${x.before}\n${x.after}`)))hits.push(name);return hits};
export const isProtectedVibeChangeAuthorized=(name,request)=>Boolean(PROTECTED_INTENT[name]?.test(clean(request)));
const changedLines=diffVibeText;

export class VibeWorkbenchController{
 constructor({root=document}={}){this.root=root;this.workspace=null;this.plan=null;this.selectedPath=null;this.selectedText='';this.state=loadState();this.changeSet=[]}
 bind(){[['openWorkspace',()=>this.openWorkspace()],['inspectProject',()=>this.inspectProject()],['planChange',()=>this.planChange()],['saveFile',()=>this.saveSelectedFile()],['restoreSnapshot',()=>this.restoreSelectedFile()],['refreshFiles',()=>this.refreshFiles()],['exportPlan',()=>this.exportPlan()],['prepareChanges',()=>this.prepareChangeSet()],['applyChanges',()=>this.applyChangeSet()]].forEach(([id,fn])=>this.bindButton(id,fn));for(const b of this.root.querySelectorAll('[data-fill]'))b.addEventListener('click',()=>{const r=this.root.getElementById('request');if(r){r.value=b.dataset.fill||'';r.focus();this.renderQuality(detectQuality(r.value))}});const editor=this.root.getElementById('editor');if(editor)editor.addEventListener('input',()=>this.captureEditorChange());const bottom=[['refreshFilesBottom',()=>this.refreshFiles()],['inspectBottom',()=>this.inspectProject()],['planBottom',()=>this.planChange()]];for(const[id,fn]of bottom){const b=this.root.getElementById(id);if(b)b.onclick=()=>fn().catch(e=>this.setStatus(`오류: ${e.message}`))}this.restoreUi();return this}
 bindButton(id,handler){const node=this.root.getElementById(id);if(node)node.addEventListener('click',async()=>{try{await handler()}catch(e){this.setStatus(`오류: ${e.message}`)}})}
 setFlow(t){const n=this.root.getElementById('flowStep');if(n)n.textContent=t}
 renderQuality(areas=[]){const set=new Set(areas);for(const[k]of QUALITY){const n=this.root.getElementById(`quality-${k}`);if(n)n.classList.toggle('on',set.has(k))}}
 async openWorkspace(){this.setFlow('1. 프로젝트 읽는 중');this.workspace=await window.pickJaewoonVibeWorkspace();const s=this.workspace.summary();this.state.workspaceOpened=true;saveState(this.state);this.renderSummary(s);this.renderFiles(s.files);this.setFlow('2. 요청 입력');this.setStatus(`프로젝트 열림 · 파일 ${s.fileCount}개`)}
 async refreshFiles(){if(!this.workspace)throw new Error('먼저 프로젝트 폴더를 열어줘');const s=await this.workspace.scan();this.renderSummary(s);this.renderFiles(s.files);this.setStatus(`새로 읽음 · ${s.fileCount}개 파일`)}
 async inspectProject(){if(!this.workspace)throw new Error('먼저 프로젝트 폴더를 열어줘');this.setFlow('3. 프로젝트 진단 중');const s=this.workspace.summary(),r=clean(this.root.getElementById('request')?.value)||'이 프로젝트 상태를 분석하고 품질 개선 방향을 알려줘';this.plan=createVibeBuildPlan({request:r,target:s.godotProject?'godot':'web'});this.renderPlan(this.plan);this.state.lastRequest=r;saveState(this.state);this.setFlow('4. 진단 완료');this.setStatus(`분석 완료 · ${s.godotProject?'Godot':'웹'} 프로젝트`)}
 async planChange(){if(!this.workspace)throw new Error('먼저 프로젝트 폴더를 열어줘');const r=clean(this.root.getElementById('request')?.value);if(!r)throw new Error('뭘 고칠지 적어줘');this.setFlow('3. 수정 범위 계산 중');const s=this.workspace.summary();this.plan=createVibeBuildPlan({request:r,target:s.godotProject?'godot':'web',rebuild:/고퀄|퀄리티|리빌드|리메이크|업그레이드|고도화|그래픽|애니|모션/i.test(r)});this.renderPlan(this.plan);this.renderQuality(detectQuality(r));this.state.lastRequest=r;saveState(this.state);this.setFlow('5. 수정 계획 완료');this.setStatus('수정 범위와 보호 대상을 계산했어')}
 rankFiles(areas){const s=this.workspace.summary(),target=s.godotProject?'godot':'web',allowed=EXT_SCORE[target];return s.files.filter(f=>f.text&&allowed[ext(f.path)]).map(f=>{const p=f.path.toLowerCase();let score=allowed[ext(f.path)]||0;if(/(^|\/)(main|game|index)\.(gd|js|html)$/i.test(f.path))score+=5;for(const area of areas)for(const word of SCORE[area]||[])if(p.includes(word))score+=2;if(/save|storage|persist/i.test(p))score-=8;if(/\.vibe-backups|node_modules|\.godot/i.test(p))score-=50;return{...f,score}}).filter(f=>f.score>0).sort((a,b)=>b.score-a.score||a.path.localeCompare(b.path)).slice(0,8)}
 async prepareChangeSet(){if(!this.workspace)throw new Error('먼저 프로젝트 폴더를 열어줘');const request=clean(this.root.getElementById('request')?.value);if(!request)throw new Error('뭘 고칠지 적어줘');const areas=detectQuality(request),ranked=this.rankFiles(areas.length?areas:['gameplay','ui']),responsibleFiles=ranked.map(f=>f.path),summary=this.workspace.summary();this.plan=createVibeBuildPlan({request,target:summary.godotProject?'godot':'web',rebuild:/고퀄|퀄리티|리빌드|리메이크|업그레이드|고도화|그래픽|애니|모션/i.test(request),responsibleFiles});this.changeSet=[];for(const f of ranked){const current=await this.workspace.read(f.path);this.changeSet.push({path:f.path,current,next:current,changed:false,score:f.score,diff:[],directives:this.plan.editBrief?.directives||[],requiredChecks:this.plan.editBrief?.requiredChecks||[]})}this.renderPlan(this.plan);this.renderChangeSet();this.setFlow('6. 책임 파일 + 실행 지시 준비');this.setStatus(`책임 파일 ${this.changeSet.length}개 확정 · 실행 지시 ${this.plan.editBrief?.directives?.length||0}개 · 편집 결과를 변경 세트에 연결할 준비 완료`);return this.changeSet}
 captureEditorChange(){if(!this.selectedPath)return;const item=this.changeSet.find(x=>x.path===this.selectedPath);if(!item)return;item.next=this.root.getElementById('editor')?.value??'';item.diff=changedLines(item.current,item.next);item.changed=item.diff.length>0;this.renderChangeSet()}
 protectionViolations(item){const request=clean(this.root.getElementById('request')?.value),hits=findProtectedVibeChanges(item.current,item.next);return hits.filter(name=>!isProtectedVibeChangeAuthorized(name,request))}
 renderChangeSet(){const n=this.root.getElementById('changeSet');if(!n)return;if(!this.changeSet.length){n.textContent='아직 준비된 변경 세트가 없어.';return}const directives=this.plan?.editBrief?.directives||[],checks=this.plan?.editBrief?.requiredChecks||[],header=[directives.length?`실행 지시: ${directives.join(' / ')}`:'',checks.length?`필수 검사: ${checks.join(' / ')}`:''].filter(Boolean).join('\n');const files=this.changeSet.map((x,i)=>{const count=x.diff?.length||0,guard=x.changed?this.protectionViolations(x):[];return`${i+1}. ${x.path} · 우선도 ${x.score}${x.changed?` · 변경 ${count}줄`: ' · 원본 유지'}${guard.length?` · 보호검사: ${guard.join(', ')}`:''}`}).join('\n');n.textContent=[header,files].filter(Boolean).join('\n\n')}
 async applyChangeSet(){if(!this.workspace)throw new Error('먼저 프로젝트 폴더를 열어줘');this.captureEditorChange();const changed=this.changeSet.filter(x=>x.changed&&x.next!==x.current);if(!changed.length)throw new Error('검토된 실제 변경 내용이 없어. 자동으로 원본을 덮어쓰지 않아');const blocked=changed.flatMap(x=>this.protectionViolations(x).map(name=>`${x.path}:${name}`));if(blocked.length)throw new Error(`기존 게임 보호 검사 차단 · ${blocked.join(', ')} · 요청에 해당 규칙 변경을 명시해야 적용돼`);this.setFlow('7. 체크포인트/원자 적용 중');const result=await this.workspace.writeManyAtomic(changed);for(const item of changed){item.current=item.next;item.changed=false;item.diff=[]}await this.refreshFiles();this.renderChangeSet();this.setFlow('8. 적용 완료 · QA 필요');this.setStatus(`변경 ${result.changed}개 원자 적용 · 백업 완료 · 실패 시 자동 rollback · 회귀 QA 필요`)}
 async selectFile(path){if(!this.workspace)throw new Error('프로젝트를 먼저 열어줘');this.captureEditorChange();const item=this.changeSet.find(x=>x.path===path);const text=item?item.next:await this.workspace.read(path);this.selectedPath=path;this.selectedText=item?item.current:text;const e=this.root.getElementById('editor');if(e)e.value=text;const n=this.root.getElementById('selectedFile');if(n)n.textContent=path;this.setStatus(`읽음 · ${path}${item?' · 변경 세트 편집 연결':''}`)}
 async saveSelectedFile(){if(!this.workspace||!this.selectedPath)throw new Error('수정할 파일을 먼저 골라줘');const e=this.root.getElementById('editor'),next=e?.value??'',item=this.changeSet.find(x=>x.path===this.selectedPath);if(item){this.captureEditorChange();throw new Error('이 파일은 변경 세트에 연결돼 있어. 보호 검사 후 검토 변경 적용을 사용해')}const r=await this.workspace.write(this.selectedPath,next,{backup:true,expectedPrevious:this.selectedText});this.selectedText=next;this.setFlow('6. 저장 완료');this.setStatus(r.changed?`저장 완료 · 자동 백업 생성 · ${this.selectedPath}`:'변경 없음');await this.refreshFiles()}
 async restoreSelectedFile(){if(!this.workspace||!this.selectedPath)throw new Error('파일을 먼저 골라줘');const item=this.changeSet.find(x=>x.path===this.selectedPath);const s=item?item.current:this.workspace.snapshots.get(this.selectedPath);if(s==null)throw new Error('이 세션에서 읽은 원본 스냅샷이 없어');const e=this.root.getElementById('editor');if(e)e.value=s;if(item){item.next=s;item.changed=false;item.diff=[];this.renderChangeSet()}this.setStatus('원본 스냅샷 복원 준비 완료')}
 exportPlan(){if(!this.plan)throw new Error('먼저 작업 분석을 해줘');const blob=new Blob([JSON.stringify(this.plan,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='vibe-plan.json';a.click();URL.revokeObjectURL(url);this.setStatus('작업 계획 저장 완료')}
 restoreUi(){const r=this.root.getElementById('request');if(r&&this.state.lastRequest)r.value=this.state.lastRequest;this.renderQuality(detectQuality(r?.value||''))}
 renderSummary(s){const n=this.root.getElementById('summary');if(!n)return;n.textContent=[`파일 ${s.fileCount}개`,`텍스트 ${s.textFiles}개`,`용량 ${Math.round(s.totalBytes/1024)}KB`,s.webProject?'웹 프로젝트':'',s.godotProject?'Godot 프로젝트':''].filter(Boolean).join(' · ')}
 renderFiles(files){const list=this.root.getElementById('files');if(!list)return;list.replaceChildren();for(const f of files.filter(x=>x.text).slice(0,500)){const b=document.createElement('button');b.type='button';b.className='fileItem';b.textContent=`${f.path} · ${Math.round(f.size/1024)}KB`;b.addEventListener('click',()=>this.selectFile(f.path).catch(e=>this.setStatus(`오류: ${e.message}`)));list.appendChild(b)}}
 renderPlan(p){const fields={intent:p.intent?.join(', ')||'분석',target:p.target,affected:textList(p.affectedSystems).join(', ')||'일반',protected:textList(p.protectedTargets).join(', ')||'없음',style:p.visualStyle?.style||'기존 스타일 유지',animation:p.animation?.states?.join(', ')||'기본 모션',mobile:p.mobile?.virtualJoystick?'터치 + 조이스틱':'확인 필요',quality:textList(p.qa).slice(0,6).join(', ')||'기본 QA'};for(const[k,v]of Object.entries(fields)){const n=this.root.getElementById(`plan-${k}`);if(n)n.textContent=v}const steps=this.root.getElementById('steps');if(steps)steps.textContent=(p.phases||[]).join('\n')}
 setStatus(m){const n=this.root.getElementById('status');if(n)n.textContent=clean(m)}
}
export function createVibeWorkbenchController(options={}){return new VibeWorkbenchController(options).bind()}
if(typeof window!=='undefined')window.createJaewoonVibeWorkbenchController=createVibeWorkbenchController;
