// 파일명: web-games/vibe-maker/workbench.js
// 역할: 브라우저 바이브 개발 작업실의 프로젝트 분석/수정/백업/비교 실행기
// 규칙: 기존 파일을 먼저 읽고, 저장 전 스냅샷 생성, 모바일 우선

import { createVibeBuildPlan } from '../../assets/vibe-build-plan.js';
const STORAGE_KEY='jaewoon-vibe-workbench';
const clean=v=>String(v??'').trim();
const loadState=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return{}}};
const saveState=s=>localStorage.setItem(STORAGE_KEY,JSON.stringify(s));
const textList=v=>Array.isArray(v)?v.filter(Boolean).map(clean):[];
const QUALITY=[['visual',['그래픽','에셋','배경','스타일','비주얼']],['animation',['애니','모션','움직임','프레임']],['vfx',['이펙트','VFX','타격','폭발','연출','파티클']],['audio',['사운드','소리','음악','BGM','효과음']],['gameplay',['재미','게임성','전투','보상','웨이브','밸런스','플레이']],['ui',['UI','UX','배치','버튼','직관','터치','조작','조이스틱']],['performance',['성능','느려','로딩','프레임','메모리','최적화']],['multiplayer',['멀티','협동','AI','NPC','동기화','온라인']]];
const detectQuality=r=>QUALITY.filter(([,w])=>w.some(x=>clean(r).toLowerCase().includes(String(x).toLowerCase()))).map(([k])=>k);
export class VibeWorkbenchController{
 constructor({root=document}={}){this.root=root;this.workspace=null;this.plan=null;this.selectedPath=null;this.selectedText='';this.state=loadState()}
 bind(){[['openWorkspace',()=>this.openWorkspace()],['inspectProject',()=>this.inspectProject()],['planChange',()=>this.planChange()],['saveFile',()=>this.saveSelectedFile()],['restoreSnapshot',()=>this.restoreSelectedFile()],['refreshFiles',()=>this.refreshFiles()],['exportPlan',()=>this.exportPlan()]].forEach(([id,fn])=>this.bindButton(id,fn));for(const b of this.root.querySelectorAll('[data-fill]'))b.addEventListener('click',()=>{const r=this.root.getElementById('request');if(r){r.value=b.dataset.fill||'';r.focus();this.renderQuality(detectQuality(r.value))}});const bottom=[['refreshFilesBottom',()=>this.refreshFiles()],['inspectBottom',()=>this.inspectProject()],['planBottom',()=>this.planChange()]];for(const[id,fn]of bottom){const b=this.root.getElementById(id);if(b)b.onclick=()=>fn().catch(e=>this.setStatus(`오류: ${e.message}`))}this.restoreUi();return this}
 bindButton(id,handler){const node=this.root.getElementById(id);if(node)node.addEventListener('click',async()=>{try{await handler()}catch(e){this.setStatus(`오류: ${e.message}`)}})}
 setFlow(t){const n=this.root.getElementById('flowStep');if(n)n.textContent=t}
 renderQuality(areas=[]){const set=new Set(areas);for(const[k]of QUALITY){const n=this.root.getElementById(`quality-${k}`);if(n)n.classList.toggle('on',set.has(k))}const list=this.root.getElementById('qualitySystems');if(list&&areas.length){list.replaceChildren(...areas.map(x=>{const s=document.createElement('span');s.className='chip';s.textContent=x;s.title='요청에서 감지된 작업 영역';return s}))}}
 async openWorkspace(){this.setFlow('1. 프로젝트 읽는 중');this.workspace=await window.pickJaewoonVibeWorkspace();const s=this.workspace.summary();this.state.workspaceOpened=true;saveState(this.state);this.renderSummary(s);this.renderFiles(s.files);this.setFlow('2. 요청 입력');this.setStatus(`프로젝트 열림 · 파일 ${s.fileCount}개`)}
 async refreshFiles(){if(!this.workspace)throw new Error('먼저 프로젝트 폴더를 열어줘');const s=await this.workspace.scan();this.renderSummary(s);this.renderFiles(s.files);this.setStatus(`새로 읽음 · ${s.fileCount}개 파일`)}
 async inspectProject(){if(!this.workspace)throw new Error('먼저 프로젝트 폴더를 열어줘');this.setFlow('3. 프로젝트 진단 중');const s=this.workspace.summary(),r=clean(this.root.getElementById('request')?.value)||'이 프로젝트 상태를 분석하고 품질 개선 방향을 알려줘';this.plan=createVibeBuildPlan({request:r,target:s.godotProject?'godot':'web'});this.renderPlan(this.plan);this.state.lastRequest=r;saveState(this.state);this.setFlow('4. 진단 완료');this.setStatus(`분석 완료 · ${s.godotProject?'Godot':'웹'} 프로젝트`)}
 async planChange(){if(!this.workspace)throw new Error('먼저 프로젝트 폴더를 열어줘');const r=clean(this.root.getElementById('request')?.value);if(!r)throw new Error('뭘 고칠지 적어줘');this.setFlow('3. 수정 범위 계산 중');const s=this.workspace.summary();this.plan=createVibeBuildPlan({request:r,target:s.godotProject?'godot':'web',rebuild:/고퀄|퀄리티|리빌드|리메이크|업그레이드|고도화|그래픽|애니|모션/i.test(r)});this.renderPlan(this.plan);this.renderQuality(detectQuality(r));this.state.lastRequest=r;saveState(this.state);this.setFlow('5. 수정 계획 완료');this.setStatus('수정 범위와 보호 대상을 계산했어')}
 async selectFile(path){if(!this.workspace)throw new Error('프로젝트를 먼저 열어줘');const text=await this.workspace.read(path);this.selectedPath=path;this.selectedText=text;const e=this.root.getElementById('editor');if(e)e.value=text;const n=this.root.getElementById('selectedFile');if(n)n.textContent=path;this.setStatus(`읽음 · ${path}`)}
 async saveSelectedFile(){if(!this.workspace||!this.selectedPath)throw new Error('수정할 파일을 먼저 골라줘');const e=this.root.getElementById('editor'),next=e?.value??'';const r=await this.workspace.write(this.selectedPath,next,{backup:true,expectedPrevious:this.selectedText});this.selectedText=next;this.setFlow('6. 저장 완료');this.setStatus(r.changed?`저장 완료 · 자동 백업 생성 · ${this.selectedPath}`:'변경 없음');await this.refreshFiles()}
 async restoreSelectedFile(){if(!this.workspace||!this.selectedPath)throw new Error('파일을 먼저 골라줘');const s=this.workspace.snapshots.get(this.selectedPath);if(s==null)throw new Error('이 세션에서 읽은 원본 스냅샷이 없어');const e=this.root.getElementById('editor');if(e)e.value=s;this.setStatus('원본 스냅샷 복원 준비 · 저장을 누르면 적용돼')}
 exportPlan(){if(!this.plan)throw new Error('먼저 작업 분석을 해줘');const blob=new Blob([JSON.stringify(this.plan,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='vibe-plan.json';a.click();URL.revokeObjectURL(url);this.setStatus('작업 계획 저장 완료')}
 restoreUi(){const r=this.root.getElementById('request');if(r&&this.state.lastRequest)r.value=this.state.lastRequest;this.renderQuality(detectQuality(r?.value||''))}
 renderSummary(s){const n=this.root.getElementById('summary');if(!n)return;n.textContent=[`파일 ${s.fileCount}개`,`텍스트 ${s.textFiles}개`,`용량 ${Math.round(s.totalBytes/1024)}KB`,s.webProject?'웹 프로젝트':'',s.godotProject?'Godot 프로젝트':''].filter(Boolean).join(' · ')}
 renderFiles(files){const list=this.root.getElementById('files');if(!list)return;list.replaceChildren();for(const f of files.filter(x=>x.text).slice(0,500)){const b=document.createElement('button');b.type='button';b.className='fileItem';b.textContent=`${f.path} · ${Math.round(f.size/1024)}KB`;b.addEventListener('click',()=>this.selectFile(f.path).catch(e=>this.setStatus(`오류: ${e.message}`)));list.appendChild(b)}}
 renderPlan(p){const fields={intent:p.intent?.join(', ')||'분석',target:p.target,affected:textList(p.affectedSystems).join(', ')||'일반',protected:textList(p.protectedTargets).join(', ')||'없음',style:p.visualStyle?.style||'기존 스타일 유지',animation:p.animation?.states?.join(', ')||'기본 모션',mobile:p.mobile?.virtualJoystick?'터치 + 조이스틱':'확인 필요',quality:textList(p.qa).slice(0,6).join(', ')||'기본 QA'};for(const[k,v]of Object.entries(fields)){const n=this.root.getElementById(`plan-${k}`);if(n)n.textContent=v}const steps=this.root.getElementById('steps');if(steps)steps.textContent=(p.phases||[]).join('\n')}
 setStatus(m){const n=this.root.getElementById('status');if(n)n.textContent=clean(m)}
}
export function createVibeWorkbenchController(options={}){return new VibeWorkbenchController(options).bind()}
if(typeof window!=='undefined')window.createJaewoonVibeWorkbenchController=createVibeWorkbenchController;
