(()=>{
if(window.__RPG_V15_PATCHED)return;window.__RPG_V15_PATCHED=true;

F.f8={n:'8번 폐허 마을',l:'Lv.13~15',bg:'#302b2a',m:[['폐허 기사',13,1250,28,60,22,180,45,2,'knight'],['잿빛 주술사',14,1500,34,52,23,220,60,2,'demon'],['거대오크',15,2000,40,46,34,400,100,1,'giantOrc']]};
F.f9={n:'9번 공동묘지',l:'Lv.16~20',bg:'#11141a',m:[]};
F.f10={n:'10번 빙결 설산',l:'Lv.21~23',bg:'#8ca8b8',m:[['빙설 늑대',21,2800,72,82,23,260,120,3,'wolf'],['얼음 해골',22,3200,78,62,22,300,140,3,'skeleton'],['빙결 오크',23,3800,84,55,27,360,170,2,'orc']]};
F.f11={n:'11번 저주받은 성',l:'Lv.24~27',bg:'#241a2d',m:[['저주받은 기사',24,4300,92,63,24,430,210,3,'knight'],['혈마법사',25,3900,88,58,23,470,230,2,'demon'],['심연의 거인',27,5600,108,50,31,620,320,1,'ogre']]};
F.cliff={n:'절벽 지대',l:'Lv.10~12',bg:'#726751',m:[['절벽 늑대',10,950,38,76,20,105,55,3,'wolf'],['바위 오크',11,1350,46,55,24,140,72,3,'orc'],['절벽 기사',12,1700,54,60,23,175,90,2,'knight']]};
F.amazon={n:'아마존',l:'Lv.9~10',bg:'#10251b',m:[['늪 악어',9,1000,40,62,25,120,0,0,'croc'],['썩은 골렘',10,1500,30,46,31,150,0,0,'golem']]};
if(!P.some(a=>a[0]==='f8'))P.push(['f8',1010,820,'8번 포탈','Lv.13~15']);
if(!P.some(a=>a[0]==='f9'))P.push(['f9',1450,820,'9번 포탈','Lv.16~20']);
WEAPONS['철 도끼'].damage=40;WEAPONS['철 도끼'].cd=.5;
WEAPONS['강철 대검']={price:700,damage:50,cd:1};WEAPONS['강철 쌍검']={price:1000,damage:35,cd:.35};
WEAPONS['빙결 대검']={price:2200,damage:75,cd:.8,hidden:true};WEAPONS['저주 쌍검']={price:2600,damage:65,cd:.32,hidden:true};WEAPONS['사신의 낫']={price:3000,damage:95,cd:1,hidden:true};
for(const k of ['강철 대검','강철 쌍검','빙결 대검','저주 쌍검','사신의 낫'])if(!(k in ownedWeapons))ownedWeapons[k]=false;
ARMORS['강철 갑옷']={price:500,hp:400};if(!('강철 갑옷' in ownedArmors))ownedArmors['강철 갑옷']=false;
SELL_PRICE['골렘 이끼']=100;SELL_PRICE['악어 비늘']=70;inv['골렘 이끼']=inv['골렘 이끼']||0;inv['악어 비늘']=inv['악어 비늘']||0;inv['회복 물약']=inv['회복 물약']||0;
let postReaper=false,graveOffered=false,reaperDefeated=false,reaperRef=null,summonCountdown=0,questKill10=0,jungleWalk=0,lastJungleX=p.x,lastJungleY=p.y;
const ALTAR={x:1425,y:950},RIVER={x:900,y:600},AMAZON_SIGN={x:1680,y:1040},CLIFF_EXIT={x:1720,y:600},hazards=[];
const hudRow=document.querySelector('#hud .row'),jobText=document.createElement('span');jobText.className='pill';jobText.textContent='미전직';hudRow.appendChild(jobText);
const skill=document.createElement('button');skill.className='btn';skill.style.cssText='right:22px;bottom:130px;width:88px;height:72px;border-radius:18px;background:#7048b7e8;font-size:12px;display:none;white-space:pre-line';document.body.appendChild(skill);
const heal=document.createElement('button');heal.className='btn';heal.textContent='물약';heal.style.cssText='right:122px;bottom:38px;width:78px;height:78px;border-radius:18px;background:#2d9b72e8;font-size:12px;display:none';document.body.appendChild(heal);
const route=document.createElement('div');route.className='overlay';route.innerHTML='<div class="panel"><h2>강길 선택</h2><p>강을 따라 어디로 갈까?</p><button id="toAmazon" class="main">아마존으로</button><button id="toCliff" class="main">절벽으로</button><button id="routeClose" class="main dark">취소</button></div>';document.body.appendChild(route);
route.querySelector('#routeClose').onclick=()=>route.style.display='none';route.querySelector('#toAmazon').onclick=()=>{route.style.display='none';enter('amazon')};route.querySelector('#toCliff').onclick=()=>{route.style.display='none';enter('cliff')};
if(!npcs.some(n=>n.k==='potion'))npcs.push({x:1180,y:1010,n:'물약상인',k:'potion'});
const TRAINERS={warrior:{zone:'town',x:610,y:530,name:'전사 전직관',job:'전사'},archer:{zone:'f8',x:1360,y:600,name:'궁수 전직관',job:'궁수'},mage:{zone:'f5',x:1630,y:170,name:'마법사 전직관',job:'마법사'}};
const hp0=maxHp;maxHp=function(){const v=hp0();return p.job==='궁수'?Math.max(1,Math.floor(v*.7)):v};const atk0=currentAtk;currentAtk=function(){const v=atk0();return p.job==='궁수'?v*1.5:v};
function nearTrainer(){let b=null,bd=82;for(const t of Object.values(TRAINERS)){if(t.zone!==zone)continue;const d=Math.hypot(p.x-t.x,p.y-t.y);if(d<bd){bd=d;b=t}}return b}
function become(job){if(p.lv<5){say('전직관','Lv.5부터 전직할 수 있다.');return}if(p.job&&p.job!=='미전직'){say('전직관','이미 '+p.job+'로 전직했다.');return}p.job=job;p.skillCd=0;if(job==='궁수')p.hp=Math.min(p.hp,maxHp());sfx('levelUp');hud();say('전직관',job+' 전직 완료!')}
function slashHit(){const ax=p.x+p.dir*40;fx.push({x:ax,y:p.y,t:.25,d:p.dir});for(const m of mons){if(m.dead)continue;if(Math.hypot(m.x-ax,m.y-p.y)<88+m.r){m.hp-=currentAtk()*3;m.hit=.15;if(m.hp<=0)kill(m)}}}
function useJobSkill(){if(!run||p.skillCd>0)return;if(p.job==='전사'){p.skillCd=10;slashHit();setTimeout(()=>{if(run)slashHit()},180);toastMsg('슬래시! 3배 공격 ×2')}else if(p.job==='마법사'){p.skillCd=30;p.hp=Math.min(maxHp(),p.hp+100);hud();toastMsg('자가회복 +100')}}
skill.onpointerdown=e=>{e.preventDefault();useJobSkill()};function skillLabel(){if(p.job==='전사')return p.skillCd>0?'슬래시\n'+Math.ceil(p.skillCd)+'초':'슬래시\n3배×2';if(p.job==='마법사')return p.skillCd>0?'자가회복\n'+Math.ceil(p.skillCd)+'초':'자가회복\n+100';return ''}
function customSpawn(spec,x,y,z){spawn(spec,x,y,z);return mons[mons.length-1]}
const baseEnter=enter;
function enterAmazon(){WORLD.w=3200;WORLD.h=2200;baseEnter('amazon');mons=[];const c=F.amazon.m[0],g=F.amazon.m[1];[[1035,1110],[1510,760],[1900,1170],[2440,910]].forEach(v=>customSpawn(c,v[0],v[1],'amazon'));[[1060,420],[2260,1540]].forEach(v=>{const m=customSpawn(g,v[0],v[1],'amazon');m.dormant=true;m.spd=0});p.x=210;p.y=1100;hud();toastMsg('거대한 아마존 지역 진입')}
function enterCliff(){WORLD.w=2000;WORLD.h=1400;baseEnter('cliff');p.x=185;p.y=700;hud();toastMsg('절벽 지대 · Lv.10~12')}
enter=function(z){if(z==='amazon'){enterAmazon();return}if(z==='cliff'){enterCliff();return}const keep=q,block=q===5&&z==='f2';if(block)q=5005;WORLD.w=z==='f9'?2850:1800;WORLD.h=z==='f9'?1900:1200;baseEnter(z);if(block){q=keep;hud()}if(z==='f9'){graveOffered=false;reaperDefeated=false;reaperRef=null;summonCountdown=0;p.x=185;p.y=600}};
const getAction0=getAction;getAction=function(){if(zone==='f4'&&Math.hypot(p.x-AMAZON_SIGN.x,p.y-AMAZON_SIGN.y)<100)return {label:'아마존 가기',kind:'amazon'};if(zone==='f7'&&Math.hypot(p.x-RIVER.x,p.y-RIVER.y)<110)return {label:'들어가기',kind:'river'};if(zone==='cliff'&&Math.hypot(p.x-CLIFF_EXIT.x,p.y-CLIFF_EXIT.y)<110)return {label:'아마존으로',kind:'cliffAmazon'};if(zone==='f9'&&!graveOffered&&!reaperDefeated&&Math.hypot(p.x-ALTAR.x,p.y-ALTAR.y)<110)return {label:'바치기',kind:'graveOffer'};return getAction0()};
const useAction0=useAction;useAction=function(){const a=getAction();if(!a)return;if(a.kind==='amazon'){enter('amazon');return}if(a.kind==='river'){route.style.display='flex';return}if(a.kind==='cliffAmazon'){enter('amazon');return}if(a.kind==='graveOffer'){graveOffered=true;summonCountdown=3;sfx('bossAggro');toastMsg('무언가가 제물을 받아들였다...');return}useAction0()};
function rewardNext(next,msg){p.g+=50;q=next;sfx('questReward');hud();toastMsg('퀘스트 완료! +50골드');if(msg)setTimeout(()=>toastMsg(msg),520)}
function allArmorsOwned(){return Object.keys(ARMORS).filter(n=>['나무 갑옷','철 갑옷','강철 갑옷'].includes(n)).every(n=>ownedArmors[n])}
function autoQuestCheck(){if(q===7&&p.lv>=5){rewardNext(8,'다음: 전직하기');return true}if(q===8&&p.job&&p.job!=='미전직'){rewardNext(9,'다음: 오우거 처치');return true}if(q===11&&allArmorsOwned()){jungleWalk=0;rewardNext(12,'다음: 정글 15초 탐험');return true}return false}
const hud0=hud;hud=function(){hud0();jobText.textContent=p.job||'미전직';if(q===5||q===5005)quest.textContent='퀘스트: 2번 사냥터에서 몬스터 1마리 처치';else if(q===6)quest.textContent='퀘스트: 아무 무기나 1개 구매';else if(q===7)quest.textContent='퀘스트: Lv.5까지 올리기';else if(q===8)quest.textContent='퀘스트: 전직하기';else if(q===9)quest.textContent='퀘스트: 오우거 처치하기';else if(q===10)quest.textContent='퀘스트: 몬스터 10마리 처치 ('+Math.min(10,questKill10)+'/10)';else if(q===11)quest.textContent='퀘스트: 갑옷 구매';else if(q===12)quest.textContent='퀘스트: 정글 15초 탐험 ('+Math.min(15,Math.floor(jungleWalk))+'/15초)';else if(q>=13)quest.textContent='메인 퀘스트 완료'};
const talk0=talkNow;talkNow=function(){const tr=nearTrainer();if(tr){become(tr.job);return}const n=nearest();if(n&&n.k==='potion'){if(p.g<70){say('물약상인','회복 물약은 70골드다.');return}p.g-=70;inv['회복 물약']++;sfx('buy');hud();say('물약상인','회복 물약 1개 구매. 체력 100을 회복한다.');return}if(n&&n.k==='chief'){if(q===4){p.g+=50;q=5;sfx('questReward');hud();say('촌장','보상 50골드. 다음은 2번 사냥터에서 몬스터 1마리 처치다.');return}if(q===5){say('촌장','2번 사냥터에서 아무 몬스터나 1마리 처치해라.');return}if(q===6){say('촌장','아무 무기나 하나 사라.');return}if(q===7){say('촌장','레벨 5까지 성장해라.');return}if(q===8){autoQuestCheck();say('촌장','전직관에게 가서 전직해라. 이미 했다면 바로 인정한다.');return}if(q===9){say('촌장','6번 사냥터의 오우거를 처치해라.');return}if(q===10){say('촌장','몬스터 10마리를 더 잡아라.');return}if(q===11){if(autoQuestCheck())return;say('촌장','갑옷을 구매해라.');return}if(q===12){say('촌장','7번 정글을 15초 동안 돌아다녀라.');return}}talk0()};
const buyW0=buyOrEquipWeapon;buyOrEquipWeapon=function(name){const before=!!ownedWeapons[name];buyW0(name);if(q===6&&!before&&ownedWeapons[name]){rewardNext(7,'다음: Lv.5 달성');autoQuestCheck()}};const buyA0=buyOrEquipArmor;buyOrEquipArmor=function(name){const before=!!ownedArmors[name];buyA0(name);if(q===11&&!before&&ownedArmors[name])rewardNext(12,'다음: 정글 15초 탐험')};heal.onpointerdown=e=>{e.preventDefault();if((inv['회복 물약']||0)<=0)return;if(p.hp>=maxHp()){toastMsg('이미 체력이 가득하다');return}inv['회복 물약']--;p.hp=Math.min(maxHp(),p.hp+100);hud();toastMsg('체력 +100')};
function unlockAfterReaper(){if(postReaper)return;postReaper=true;if(!P.some(a=>a[0]==='f10'))P.push(['f10',520,1040,'10번 포탈','Lv.21~23']);if(!P.some(a=>a[0]==='f11'))P.push(['f11',760,1040,'11번 포탈','Lv.24~27']);for(const n of ['빙결 대검','저주 쌍검','사신의 낫'])WEAPONS[n].hidden=false;ARMORS['빙결 갑옷']={price:1800,hp:700};ARMORS['사신 망토']={price:2600,hp:950};if(!('빙결 갑옷' in ownedArmors))ownedArmors['빙결 갑옷']=false;if(!('사신 망토' in ownedArmors))ownedArmors['사신 망토']=false;toastMsg('10·11번 포탈과 새로운 장비가 해금됐다!')}
function spawnReaper(){if(zone!=='f9'||reaperRef||reaperDefeated)return;const m={n:'사신',lv:20,x:ALTAR.x,y:ALTAR.y-130,hp:3000,mhp:3000,a:66,spd:72,r:48,xp:0,g:0,type:'reaper',baseType:'reaper',z:'f9',hit:0,dead:false,shootCd:0,animState:'idle',animFrame:0,animTick:0,deathAge:0,dir:-1,aggroed:true,specialCd:2.5};mons.push(m);reaperRef=m;sfx('bossAggro');toastMsg('사신 강림! Lv.20')}
function hazard(x,y,r,delay,damage,kind){hazards.push({x,y,r,t:delay,damage,kind,hit:false})}
function bossPattern(m,dt){m.specialCd=(m.specialCd==null?3:m.specialCd-dt);if(m.specialCd>0)return;if(m.type==='slimeKing'){hazard(p.x,p.y,135,.9,26,'slime');m.specialCd=6;toastMsg('슬라임 왕 점프 내려찍기!')}else if(m.type==='giantCaveSlime'){for(const [dx,dy] of [[0,0],[90,50],[-90,-45]])hazard(p.x+dx,p.y+dy,72,.8,22,'acid');m.specialCd=7;toastMsg('거대 슬라임 산성 분열!')}else if(m.type==='ogre'){hazard(m.x,m.y,185,.85,58,'smash');m.specialCd=7.5;toastMsg('오우거 대지 강타!')}else if(m.type==='giantOrc'){const a=Math.atan2(p.y-m.y,p.x-m.x);m.x=Math.max(80,Math.min(WORLD.w-80,m.x+Math.cos(a)*190));m.y=Math.max(80,Math.min(WORLD.h-80,m.y+Math.sin(a)*190));hazard(m.x,m.y,165,.55,72,'charge');m.specialCd=8;toastMsg('거대오크 돌진 강타!')}else if(m.type==='reaper'){m.x=Math.max(90,Math.min(WORLD.w-90,p.x-p.dir*135));m.y=Math.max(90,Math.min(WORLD.h-90,p.y));hazard(p.x,p.y,165,.6,66,'reaper');if(m.hp<m.mhp*.5){hazard(p.x+130,p.y,90,1,44,'soul');hazard(p.x-130,p.y,90,1,44,'soul')}m.specialCd=m.hp<m.mhp*.5?4.5:6;toastMsg('사신 · 영혼 참격!')}}
function updateHazards(dt){for(let i=hazards.length-1;i>=0;i--){const h=hazards[i];h.t-=dt;if(h.t<=0&&!h.hit){h.hit=true;if(Math.hypot(p.x-h.x,p.y-h.y)<h.r+p.r)damage(h.damage)}if(h.t<-.3)hazards.splice(i,1)}}
const kill0=kill;kill=function(m){const alive=!m.dead,oldDrops=drops.length,kz=zone,kt=m.type;kill0(m);if(!alive||!m.dead)return;if(kt==='croc'){if(drops.length>oldDrops)drops.splice(oldDrops);drops.push({x:m.x,y:m.y,item:'악어 비늘',t:20})}if(kt==='golem'){if(drops.length>oldDrops)drops.splice(oldDrops);drops.push({x:m.x,y:m.y,item:'골렘 이끼',t:20})}if(kt==='reaper'){if(drops.length>oldDrops)drops.splice(oldDrops);reaperDefeated=true;reaperRef=null;unlockAfterReaper();setTimeout(()=>{if(zone==='f9')say('사신','꽤 실력이 좋군. 다음에는 봐주는 건 없다.')},320);setTimeout(()=>toastMsg('사신이 어둠 속으로 사라졌다'),1550)}if(q===5&&kz==='f2'){rewardNext(6,'다음: 아무 무기나 구매');return}if(q===9&&kt==='ogre'){questKill10=0;rewardNext(10,'다음: 몬스터 10마리 처치');return}if(q===10){questKill10++;if(questKill10>=10){rewardNext(11,'다음: 갑옷 구매');autoQuestCheck()}else hud()}};
const update0=update;update=function(dt){p.skillCd=Math.max(0,(p.skillCd||0)-dt);if(zone==='amazon')for(const m of mons)if(m.type==='golem'&&m.dormant&&!m.dead&&Math.hypot(p.x-m.x,p.y-m.y)<210){m.dormant=false;m.spd=46;toastMsg('썩은 골렘이 깨어났다!')}update0(dt);if(summonCountdown>0){summonCountdown-=dt;if(summonCountdown<=0){summonCountdown=0;spawnReaper()}}for(const m of mons)if(!m.dead&&['slimeKing','giantCaveSlime','ogre','giantOrc','reaper'].includes(m.type))bossPattern(m,dt);updateHazards(dt);let changed=true,g=0;while(changed&&g++<3)changed=autoQuestCheck();if(q===12){if(zone==='f7'){const moved=Math.hypot(p.x-lastJungleX,p.y-lastJungleY)>1.2;if(moved)jungleWalk+=dt;lastJungleX=p.x;lastJungleY=p.y;if(jungleWalk>=15){jungleWalk=15;rewardNext(13,'메인 퀘스트 완료!')}else hud()}else{lastJungleX=p.x;lastJungleY=p.y}}skill.style.display=(p.job==='전사'||p.job==='마법사')?'block':'none';skill.textContent=skillLabel();heal.style.display=(inv['회복 물약']||0)>0?'block':'none'};
MPALETTE.giantOrc=['#52703b','#91a85a','#26351f'];MPALETTE.croc=['#315d3c','#597f45','#162e21'];MPALETTE.golem=['#55584f','#7c806e','#2d302b'];MPALETTE.reaper=['#09080d','#2b1638','#d8d3c9'];
function riverDraw(){ctx.fillStyle='#315f78';ctx.fillRect(70,520,1660,160);ctx.fillStyle='#5d899a';for(let x=100;x<1700;x+=110){ctx.beginPath();ctx.ellipse(x,550+(x%3)*30,45,8,0,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#765b3c';ctx.fillRect(840,505,120,190);ctx.fillStyle='#d2b37b';ctx.fillRect(850,515,100,170);ctx.fillStyle='#fff';ctx.font='bold 13px sans-serif';ctx.textAlign='center';ctx.fillText('강길 입구',900,495);ctx.textAlign='left'}
function cliffDraw(){ctx.fillStyle='#5d5545';for(let i=0;i<28;i++){const x=260+((i*173)%1450),y=130+((i*229)%1050);rock(x,y,.8+(i%3)*.2)}ctx.fillStyle='#3a3228';ctx.fillRect(1760,90,170,1220);ctx.fillStyle='#fff';ctx.font='bold 14px sans-serif';ctx.fillText('아마존으로 이어지는 절벽길',1550,540)}
function amazonDraw(){ctx.fillStyle='#10251b';ctx.fillRect(0,0,WORLD.w,WORLD.h);const lakes=[[1480,1080,360,270],[2500,650,300,225],[860,1650,250,200]];for(const [x,y,rx,ry] of lakes){ctx.fillStyle='#16382d';ctx.strokeStyle='#53634a';ctx.lineWidth=18;ctx.beginPath();ctx.ellipse(x,y,rx,ry,.13,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='#2c5a49';ctx.lineWidth=8;ctx.beginPath();ctx.ellipse(x,y,rx-22,ry-20,.13,0,Math.PI*2);ctx.stroke()}for(let i=0;i<85;i++){const x=180+((i*397)%2850),y=130+((i*257)%1980);if(i%3===0)palm(x,y,1.1);else if(i%3===1)banana(x,y,1.15);else tropical(x,y,1.25)}}
function graveDraw(){ctx.fillStyle='#0d1015';ctx.fillRect(0,0,WORLD.w,WORLD.h);ctx.strokeStyle='#3b3d44';ctx.lineWidth=7;ctx.strokeRect(70,70,WORLD.w-140,WORLD.h-140);for(let i=0;i<78;i++){const x=230+((i*347)%2320),y=150+((i*521)%1550);if(Math.hypot(x-ALTAR.x,y-ALTAR.y)<240)continue;ctx.fillStyle='#484b50';ctx.fillRect(x-17,y-30,34,42);if(i%3===0){ctx.fillRect(x-4,y-54,8,25);ctx.fillRect(x-13,y-47,26,7)}}ctx.save();ctx.translate(ALTAR.x,ALTAR.y);ctx.fillStyle='#1b151e';ctx.beginPath();ctx.arc(0,0,105,0,Math.PI*2);ctx.fill();ctx.strokeStyle=graveOffered?'#9f3dff':'#58455e';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,80,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#4d4751';ctx.fillRect(-48,-25,96,50);ctx.fillStyle='#d6c4e2';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillText('제물 놓기',0,5);ctx.restore();ctx.textAlign='left'}
function ruinedDraw(){for(let i=0;i<10;i++){const x=260+((i*181)%1300),y=160+((i*257)%850);ctx.fillStyle='#1f1b1a';ctx.fillRect(x-35,y-23,70,46);ctx.fillStyle='#493b34';ctx.fillRect(x-45,y-31,90,12)}for(let i=0;i<20;i++)rock(180+((i*223)%1450),120+((i*179)%930),.6)}
function amazonSign(){ctx.fillStyle='#4c3424';ctx.fillRect(AMAZON_SIGN.x-7,AMAZON_SIGN.y-5,14,55);ctx.fillStyle='#735030';ctx.fillRect(AMAZON_SIGN.x-70,AMAZON_SIGN.y-50,140,48);ctx.fillStyle='#ffe49a';ctx.font='bold 13px sans-serif';ctx.textAlign='center';ctx.fillText('아마존으로 가는곳',AMAZON_SIGN.x,AMAZON_SIGN.y-22);ctx.textAlign='left'}
const decor0=drawDecor;drawDecor=function(z){if(z==='f9'){graveDraw();return}if(z==='amazon'){amazonDraw();return}if(z==='cliff'){cliffDraw();return}if(z==='f8'){ruinedDraw();return}decor0(z);if(z==='f7')riverDraw();if(z==='f4')amazonSign()};
function crocSprite(m){ctx.save();ctx.translate(m.x,m.y);ctx.scale(m.dir||1,1);shadow(0,5,34);ctx.fillStyle='#315d3c';ctx.beginPath();ctx.ellipse(0,0,42,15,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-35,0);ctx.lineTo(-70,-7);ctx.lineTo(-42,8);ctx.fill();ctx.fillStyle='#496f46';ctx.fillRect(24,-12,35,23);ctx.fillStyle='#e9e1c7';for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(30+i*6,10);ctx.lineTo(33+i*6,17);ctx.lineTo(36+i*6,10);ctx.fill()}ctx.fillStyle='#ffd33d';ctx.beginPath();ctx.arc(48,-7,3,0,Math.PI*2);ctx.fill();ctx.restore()}
function golemSprite(m){ctx.save();ctx.translate(m.x,m.y);shadow(0,8,32);ctx.fillStyle=m.dormant?'#55584f':'#666b5e';ctx.beginPath();ctx.moveTo(-35,18);ctx.lineTo(-29,-28);ctx.lineTo(0,-43);ctx.lineTo(34,-23);ctx.lineTo(40,20);ctx.closePath();ctx.fill();if(!m.dormant){ctx.strokeStyle='#62665b';ctx.lineWidth=13;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-22,-10);ctx.lineTo(-48,18);ctx.moveTo(23,-10);ctx.lineTo(49,18);ctx.stroke();ctx.fillStyle='#ffda3b';ctx.shadowColor='#ff8a16';ctx.shadowBlur=12;ctx.fillRect(-15,-19,8,5);ctx.fillRect(7,-19,8,5)}ctx.restore()}
function reaperSprite(m){const att=m.animState==='attack'?Math.sin((m.animFrame||0)/33*Math.PI):0;ctx.save();ctx.translate(m.x,m.y);ctx.scale((m.dir||1)*1.5,1.5);shadow(0,10,50);ctx.shadowColor='#8f38ff';ctx.shadowBlur=26;ctx.fillStyle='#08070d';ctx.beginPath();ctx.moveTo(-48,43);ctx.lineTo(-40,-34);ctx.quadraticCurveTo(0,-92,42,-33);ctx.lineTo(52,45);ctx.lineTo(30,35);ctx.lineTo(15,60);ctx.lineTo(0,38);ctx.lineTo(-18,60);ctx.lineTo(-31,35);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#d7d1c7';ctx.beginPath();ctx.ellipse(0,-48,15,19,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff244f';ctx.shadowColor='#ff244f';ctx.shadowBlur=16;ctx.fillRect(-8,-52,5,3);ctx.fillRect(3,-52,5,3);ctx.shadowBlur=0;ctx.save();ctx.translate(48,-5);ctx.rotate(-.55+att*1.25);ctx.strokeStyle='#342b39';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(0,54);ctx.lineTo(72,-82);ctx.stroke();ctx.fillStyle='#d7dce4';ctx.shadowColor='#b65cff';ctx.shadowBlur=20;ctx.beginPath();ctx.moveTo(65,-82);ctx.quadraticCurveTo(123,-104,147,-61);ctx.quadraticCurveTo(109,-77,79,-44);ctx.closePath();ctx.fill();ctx.restore();ctx.restore()}
const sprite0=drawMonsterSprite;drawMonsterSprite=function(m){if(m.type==='croc'){crocSprite(m);return}if(m.type==='golem'){golemSprite(m);return}if(m.type==='reaper'){reaperSprite(m);return}sprite0(m)};
const portal0=portal;portal=function(px,py,a,b,back=false){if(a==='9번 포탈'){ctx.save();ctx.translate(px,py);ctx.fillStyle='#24252b';ctx.fillRect(-72,-80,25,125);ctx.fillRect(47,-80,25,125);ctx.beginPath();ctx.arc(0,-72,60,Math.PI,0);ctx.fill();ctx.fillStyle='#050308';ctx.beginPath();ctx.arc(0,-67,45,Math.PI,0);ctx.lineTo(45,35);ctx.lineTo(-45,35);ctx.closePath();ctx.fill();ctx.strokeStyle='#8b3dcc';ctx.lineWidth=5;ctx.shadowColor='#a244ff';ctx.shadowBlur=18;ctx.beginPath();ctx.arc(0,-67,43,Math.PI,0);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#c8c2b5';ctx.beginPath();ctx.arc(0,-92,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 14px sans-serif';ctx.textAlign='center';ctx.fillText('9번 공동묘지',0,58);ctx.fillStyle='#e7c1ff';ctx.font='bold 12px sans-serif';ctx.fillText('Lv.16~20',0,74);ctx.restore();ctx.textAlign='left';return}portal0(px,py,a,b,back)};
function drawTrainer(t){drawHuman(t.x,t.y,'smith',Math.floor(performance.now()/45)%34,'idle',false);ctx.fillStyle='#17120e';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillText(t.name,t.x,t.y-62);ctx.fillStyle='#ffe26e';ctx.font='bold 10px sans-serif';ctx.fillText('Lv.5 전직',t.x,t.y-48);ctx.textAlign='left'}
const draw0=draw;draw=function(){draw0();ctx.save();ctx.translate(-cam.x,-cam.y);for(const t of Object.values(TRAINERS))if(t.zone===zone)drawTrainer(t);for(const h of hazards){ctx.globalAlpha=.35+.2*Math.sin(performance.now()/80);ctx.strokeStyle=h.kind==='reaper'||h.kind==='soul'?'#c05cff':h.kind==='acid'?'#7cd85b':'#ff6b52';ctx.lineWidth=6;ctx.beginPath();ctx.arc(h.x,h.y,h.r,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.12;ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.arc(h.x,h.y,h.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}ctx.restore();if(zone==='f9'&&summonCountdown>0){ctx.fillStyle='#0008';ctx.fillRect(0,0,W,H);ctx.fillStyle='#d9b3ff';ctx.font='900 42px sans-serif';ctx.textAlign='center';ctx.fillText(Math.ceil(summonCountdown),W/2,H/2);ctx.font='900 15px sans-serif';ctx.fillText('무언가가 다가온다...',W/2,H/2+32);ctx.textAlign='left'}};
const weapon0=weaponDraw;weaponDraw=function(){if(!['강철 대검','강철 쌍검','빙결 대검','저주 쌍검','사신의 낫'].includes(p.weapon)){weapon0();return}const swing=p.animState==='attack'?Math.sin(p.animFrame/33*Math.PI):0;ctx.save();ctx.translate(p.x,p.y-10);ctx.scale(p.dir,1);ctx.rotate(-.8+swing*1.55);if(p.weapon==='사신의 낫'){ctx.strokeStyle='#3b3140';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(5,10);ctx.lineTo(58,-42);ctx.stroke();ctx.fillStyle='#d5dbe5';ctx.beginPath();ctx.moveTo(54,-44);ctx.quadraticCurveTo(90,-58,105,-30);ctx.quadraticCurveTo(80,-40,61,-20);ctx.closePath();ctx.fill()}else{const icy=p.weapon==='빙결 대검',dual=p.weapon.includes('쌍검');ctx.fillStyle=icy?'#bceeff':p.weapon==='저주 쌍검'?'#c47cff':'#d9dde2';ctx.fillRect(8,-4,48,8);ctx.fillRect(48,-9,13,18);ctx.fillStyle='#6d4e2e';ctx.fillRect(2,-6,9,13);if(dual){ctx.rotate(-.42);ctx.fillStyle=p.weapon==='저주 쌍검'?'#c47cff':'#d9dde2';ctx.fillRect(5,8,44,7)}}ctx.restore()};
const reset0=reset;reset=function(){reset0();p.job='미전직';p.skillCd=0;postReaper=false;graveOffered=false;reaperDefeated=false;reaperRef=null;summonCountdown=0;questKill10=0;jungleWalk=0;lastJungleX=p.x;lastJungleY=p.y;P.splice(0,P.length,...P.filter(a=>a[0]!=='f10'&&a[0]!=='f11'));for(const n of ['빙결 대검','저주 쌍검','사신의 낫'])WEAPONS[n].hidden=true;delete ARMORS['빙결 갑옷'];delete ARMORS['사신 망토'];hud()};
if(!p.job)p.job='미전직';p.skillCd=p.skillCd||0;hud();toastMsg('대충 RPG 대형 업데이트 적용');
})();