from pathlib import Path

engine=Path('web-games/_shared/vibe2-final.js')
s=engine.read_text()
old="function renderStory(){const names=['회색 숲','침묵의 성문','수정 광산','왕도 탈환','엘도리아의 심장'];stats([['HP',S.hp],['CHAPTER',Math.min(5,S.chapter)+'/5'],['GOLD',S.gold],['POWER',S.power]]);buttons(['탐색','전투','휴식 (5G)','장비 강화 (15G)','전진 전투']);const b=$('.board');b.dataset.area=`chapter-${Math.min(5,S.chapter)}-route-${S.progress||0}`;b.innerHTML=`<div style=\"padding:25px 12px;text-align:center\"><div style=\"font-size:54px\">${['🌲','🏰','💎','👑','🐉'][Math.min(4,S.chapter-1)]}</div><h2>${names[Math.min(4,S.chapter-1)]}</h2><p style=\"color:#bcd0df;line-height:1.6\">${C.story||'엘도리아를 되찾기 위한 여정이 계속된다.'}</p></div>`;$('.bar i').style.width=((S.chapter-1)/5*100)+'%'}"
new="const storyChapters=['회색 숲','침묵의 성문','수정 광산','왕도 탈환','엘도리아의 심장'];const storyGuides=['리아','카엘','미라','세렌','아르딘'];const storyQuests=['실종된 정찰대의 흔적을 찾아라','침묵의 성문을 여는 문장을 밝혀라','수정 광산의 봉인을 해제하라','왕도의 저항군과 합류하라','엘도리아의 심장을 지켜라'];const storyClues=['수호자와 대화해 첫 단서를 찾기','발견한 단서를 따라 다음 흔적 조사','퀘스트 정보를 정리하고 전투 준비','마지막 단서를 확인하고 주요 전투로 이동'];\nfunction renderStory(){const chapter=Math.min(5,S.chapter),clue=S.progress||0,guide=storyGuides[chapter-1],quest=storyQuests[chapter-1];stats([['HP',S.hp],['CHAPTER',chapter+'/5'],['GOLD',S.gold],['POWER',S.power]]);buttons(['탐색','전투','휴식 (5G)','장비 강화 (15G)','전진 전투']);const talk=$('#a0');talk.dataset.interactable='true';talk.dataset.interactionTarget=`story-guide-${chapter}`;talk.dataset.dialogueState=String(clue);const b=$('.board');b.dataset.area=`chapter-${chapter}-route-${clue}`;b.innerHTML=`<div style=\"padding:18px 12px;text-align:center\"><div style=\"font-size:50px\">${['🌲','🏰','💎','👑','🐉'][chapter-1]}</div><h2>${storyChapters[chapter-1]}</h2><p style=\"color:#bcd0df;line-height:1.55\">${C.story||'엘도리아를 되찾기 위한 여정이 계속된다.'}</p><div data-objective=\"chapter-${chapter}-quest-main\" style=\"margin:9px 0;padding:8px;border-radius:10px;background:#17354b;text-align:left\">주요 퀘스트 · ${quest}</div><div data-objective=\"chapter-${chapter}-clue-${clue}\" style=\"margin:7px 0;padding:8px;border-radius:10px;background:#122b40;text-align:left\">현재 목표 · ${storyClues[clue%storyClues.length]}</div><div data-npc=\"${guide}\" data-interaction-target=\"story-guide-${chapter}\" data-dialogue-state=\"${clue}\" data-state=\"${clue>0?'clue-shared':'waiting'}\" style=\"margin-top:9px;padding:9px;border:1px solid #31516a;border-radius:10px;text-align:left\"><b>${guide}</b> · ${clue===0?'주변을 함께 살펴보자. 중요한 흔적이 있을 거야.':`단서 ${clue}개를 확인했어. 퀘스트 목표에 가까워지고 있어.`}</div></div>`;$('.bar i').style.width=((chapter-1)/5*100)+'%'}"
if s.count(old)!=1: raise SystemExit(f'renderStory target count={s.count(old)}')
s=s.replace(old,new)
old="function storyBattle(){const loss=Math.max(3,16-S.power*3);S.hp-=loss;S.gold+=8+S.chapter*2;S.score+=20;S.chapter++;if(S.chapter>5){end(true,'엘도리아 최종장을 완료했다! 왕국에 평화가 돌아왔다.');return true}if(S.hp<=0){end(false,'여정 중 쓰러졌다.');return true}log(`전투 승리 · 피해 ${loss}`);return false}"
new="function storyBattle(){const loss=Math.max(3,16-S.power*3);S.hp-=loss;S.gold+=8+S.chapter*2;S.score+=20;S.chapter++;S.progress=0;if(S.chapter>5){end(true,'엘도리아 최종장을 완료했다! 왕국에 평화가 돌아왔다.');return true}if(S.hp<=0){end(false,'여정 중 쓰러졌다.');return true}log(`전투 승리 · 피해 ${loss} · 다음 퀘스트가 열렸다.`);return false}"
if s.count(old)!=1: raise SystemExit(f'storyBattle target count={s.count(old)}')
s=s.replace(old,new)
old="function actStory(i){if(i===0){S.progress=(S.progress+1)%4;S.gold+=4+S.chapter;S.score+=5;log('지역을 탐색해 단서를 찾았다.')}else if(i===1||i===4){storyBattle()}else if(i===2){if(S.gold<5)return failed('골드가 부족하다.');S.gold-=5;S.hp=clamp(S.hp+28,0,100);log('야영지에서 휴식했다.')}else{if(S.gold<15)return failed('골드가 부족하다.');S.gold-=15;S.power++;log('장비를 강화했다.')}if(!S.ended){commonProgress();render()}}"
new="function actStory(i){if(i===0){S.progress=(S.progress+1)%4;S.gold+=4+S.chapter;S.score+=5;const guide=storyGuides[Math.min(4,S.chapter-1)];log(`${guide}와 대화하며 지역을 탐색해 퀘스트 단서를 찾았다.`)}else if(i===1||i===4){storyBattle()}else if(i===2){if(S.gold<5)return failed('골드가 부족하다.');S.gold-=5;S.hp=clamp(S.hp+28,0,100);log('야영지에서 휴식했다.')}else{if(S.gold<15)return failed('골드가 부족하다.');S.gold-=15;S.power++;log('장비를 강화했다.')}if(!S.ended){commonProgress();render()}}"
if s.count(old)!=1: raise SystemExit(f'actStory target count={s.count(old)}')
engine.write_text(s.replace(old,new))

test=Path('qa/company-development-web-runtime.test.mjs')
t=test.read_text()
anchor="test('shared preserved engine binds more than five approved scopes without model regeneration',async()=>{"
addition="""test('Eldoria story runtime exposes changing quest objectives and NPC dialogue interaction evidence',()=>{\n  const source=fs.readFileSync('web-games/_shared/vibe2-final.js','utf8');\n  assert.match(source,/data-objective=\\\"chapter-\\$\\{chapter\\}-quest-main/);\n  assert.match(source,/data-interaction-target=\\\"story-guide-\\$\\{chapter\\}/);\n  assert.match(source,/talk\\.dataset\\.interactionTarget=`story-guide-\\$\\{chapter\\}`/);\n  assert.match(source,/talk\\.dataset\\.dialogueState=String\\(clue\\)/);\n  assert.match(source,/S\\.progress=0;if\\(S\\.chapter>5\\)/);\n});\n\n"""+anchor
if t.count(anchor)!=1: raise SystemExit(f'test anchor count={t.count(anchor)}')
test.write_text(t.replace(anchor,addition))
