import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import {
  buildPrototypeRequest,
  conceptCreatedOnKstDate,
  createOperationalCandidate,
  detectCompletedIncubatorArtbook,
  enqueueOperationalArtbook,
  evaluateOperationalConceptQuality,
  nextPortfolioProjectId,
  normalizeIncubatorState,
  normalizeOperationalConceptProposal,
  qualityAttemptsOnKstDate,
  quarantineLowQualityCandidate,
  registerPrototypeAfterArtbook,
  validateOperationalConcept,
} from '../tools/autonomous-new-game-incubator.mjs';

const concept={name:'시간흔적 원정대',slug:'time-trace-expedition',identitySentence:'지나간 이동 경로가 다음 원정의 지형과 적 배치를 다시 만든다.',coreLoop:'탐험한다→전투한다→시간흔적을 남긴다→변형된 지형을 재탐험한다',storyHook:'붕괴한 시간층을 복구하려는 원정대가 자신이 남긴 과거의 흔적과 경쟁한다.',signatureSystems:['시간흔적 지도: 플레이어가 지나간 경로가 다음 원정의 벽·다리·위험지대로 굳어진다.'],signatureScenes:['침수된 역에서 어제의 이동선이 오늘의 다리가 된다.','보스가 플레이어가 남긴 안전 경로를 역으로 추적해 붕괴시킨다.','마지막 도시에서 여러 원정의 흔적이 겹쳐 하나의 탈출 지형을 만든다.'],worldRules:['r1','r2','r3','r4','r5'],forbiddenPatterns:['색놀이','왕복','숫자보스'],prototypeHypothesis:'이전 이동이 다음 판의 지형을 바꾸면 이동 선택 자체가 재도전 전략이 된다.',risks:['설명 복잡','성능'],styleProfile:'시간 균열 지도 + 폐허 원정 기록'};
const portfolio=()=>({version:1,projects:[{id:'P0009',slug:'monster-adventure',name:'몬스터 어드벤처'}]});
const state=()=>({version:2,status:'ACTIVE',nextCandidateNumber:1,candidates:[]});

test('concept contract, quality and P0010 reservation',()=>{assert.equal(validateOperationalConcept(concept).pass,true);assert.equal(evaluateOperationalConceptQuality(concept).pass,true);assert.equal(nextPortfolioProjectId(portfolio()),'P0010');const c=createOperationalCandidate(state(),portfolio(),concept);assert.equal(c.reservedProjectId,'P0010');assert.equal(c.status,'CONCEPT_CREATED');});
test('placeholder company meta concept is blocked before artbook investment',()=>{const bad={...concept,name:'재운컴퍼니 신규게임 후보 1개',identitySentence:'회사가 신뢰를 구축한다.',coreLoop:'플레이어의 전략적 역할을 강화하고 경험을 제공합니다.',signatureSystems:['재운컴퍼니 신규게임 후보 1개: 선택 결과가 다음 플레이 상태를 바꾸는 핵심 연계 시스템'],signatureScenes:['재운컴퍼니 신규게임 후보 1개 시작 장면: x','재운컴퍼니 신규게임 후보 1개 중반 장면: y','재운컴퍼니 신규게임 후보 1개 검증 장면: z']};const q=evaluateOperationalConceptQuality(bad);assert.equal(q.pass,false);assert.ok(q.reasons.includes('PLACEHOLDER_OR_COMPANY_TITLE'));assert.ok(q.reasons.includes('CORE_LOOP_NOT_ACTION_SEQUENCE'));assert.throws(()=>createOperationalCandidate(state(),portfolio(),bad),/품질게이트 실패/);});
test('only one operational candidate at a time',()=>{const s=state(),p=portfolio();createOperationalCandidate(s,p,concept);assert.throws(()=>createOperationalCandidate(s,p,{...concept,name:'다른 시간흔적',slug:'other-trace'}),/동시 신규게임 후보/);});
test('candidate enters existing artbook queue without production approval',()=>{const c=createOperationalCandidate(state(),portfolio(),concept),q={games:[],queueOrder:['survival'],currentDailyTarget:'survival'};enqueueOperationalArtbook(c,q);assert.equal(c.status,'ARTBOOK_QUEUED');assert.equal(q.queueOrder[1],c.artbookGameId);const g=q.games[0];assert.equal(g.source,'INCUBATOR_METADATA_ONLY');assert.equal(g.formalProductionAllowed,false);assert.equal(g.incubatorConcept.identitySentence,concept.identitySentence);});
test('low-quality queued candidate is preserved but removed from investment queue',()=>{const c={id:'NG00001',status:'ARTBOOK_QUEUED',artbookGameId:'incubator-p0010-bad',concept:{...concept,name:'신규게임 후보 1개',coreLoop:'경험을 개선합니다.',signatureSystems:['신규게임 후보 1개: 경험을 개선합니다.의 선택 결과가 다음 플레이 상태를 바꾸는 핵심 연계 시스템'],signatureScenes:['신규게임 후보 1개 시작 장면: x','신규게임 후보 1개 중반 장면: y','신규게임 후보 1개 검증 장면: z']}};const q={queueOrder:['a',c.artbookGameId,'b'],games:[{gameId:c.artbookGameId,status:'QUEUED'}]};const r=quarantineLowQualityCandidate(c,q,'2026-09-09T00:00:00Z');assert.equal(r.quarantined,true);assert.equal(c.status,'REDESIGN_REQUIRED');assert.equal(q.queueOrder.includes(c.artbookGameId),false);assert.equal(q.games[0].status,'REDESIGN_REQUIRED');});
test('quality-rejected attempt does not consume the one valid concept slot',()=>{const s=state();s.candidates.push({id:'NG00001',status:'REDESIGN_REQUIRED',qualityGate:{pass:false},createdAt:'2026-09-08T20:00:00Z'});assert.equal(conceptCreatedOnKstDate(s,'2026-09-09'),false);assert.equal(qualityAttemptsOnKstDate(s,'2026-09-09'),1);});
test('incomplete artbook cannot materialize P0010',()=>{const c=createOperationalCandidate(state(),portfolio(),concept);c.status='ARTBOOK_QUEUED';assert.equal(detectCompletedIncubatorArtbook(c,{artbooks:[]}).complete,false);const p=portfolio();const r=registerPrototypeAfterArtbook(c,p,{artbooks:[]});assert.equal(r.registered,false);assert.equal(p.projects.length,1);});
test('5-department completed artbook materializes prototype registration only',()=>{const c=createOperationalCandidate(state(),portfolio(),concept);c.status='ARTBOOK_QUEUED';const opinions=Object.fromEntries(['planning','graphics','development','qa','balance'].map(role=>[role,{reviewsReceived:5}]));const registry={artbooks:[{id:'ab1',gameId:c.artbookGameId,status:'completed-artbook',productionApproval:false,cuts:Array.from({length:10},(_,i)=>({no:i+1})),departmentOpinions:opinions,collaboration:{allFiveDepartmentsReviewed:true},sourceFile:'artbook.json'}]};const p=portfolio();const r=registerPrototypeAfterArtbook(c,p,registry,'2026-09-09T00:00:00Z');assert.equal(r.registered,true);assert.equal(p.projects.at(-1).id,'P0010');assert.equal(p.projects.at(-1).mode,'PROTOTYPE');assert.equal(p.projects.at(-1).publicReleaseApproved,false);const request=buildPrototypeRequest(c,p);assert.equal(request.candidateBranchOnly,true);assert.equal(request.publicStableWrite,false);});
test('production-approved flag is not accepted as incubator evidence',()=>{const c=createOperationalCandidate(state(),portfolio(),concept);c.status='ARTBOOK_QUEUED';const registry={artbooks:[{id:'ab1',gameId:c.artbookGameId,status:'completed-artbook',productionApproval:true,cuts:Array(10).fill({}),departmentOpinions:{},collaboration:{allFiveDepartmentsReviewed:true}}]};assert.equal(detectCompletedIncubatorArtbook(c,registry).complete,false);});
test('legacy empty incubator state migrates without inventing a candidate',()=>{const migrated=normalizeIncubatorState({version:1,lastProjectNumber:9,activeConceptId:null,concepts:[],lastRunAt:null});assert.equal(migrated.version,2);assert.deepEqual(migrated.candidates,[]);assert.equal(migrated.nextCandidateNumber,1);assert.equal(migrated.lastProjectNumber,9);});
test('small-model proposal can complete list contract but synthetic-only identity remains quality-gated',()=>{const raw={name:'빛의 잔향',identitySentence:'빛을 남긴 이동 경로가 다음 전투의 지형이 된다.',coreLoop:'이동한다→잔향을 남긴다→전투한다→경로를 재작성한다',storyHook:'빛이 사라진 도시의 마지막 배달부',prototypeHypothesis:'이동 경로가 다음 전투를 바꾸면 이동 자체가 전략이 된다.',styleProfile:'네온 지도 + 어두운 도시'};const normalized=normalizeOperationalConceptProposal(raw);assert.equal(normalized.identitySentence,raw.identitySentence);assert.ok(normalized.signatureSystems.length>=1);assert.equal(validateOperationalConcept(normalized).pass,true);assert.equal(evaluateOperationalConceptQuality(normalized).pass,false);assert.ok(evaluateOperationalConceptQuality(normalized).reasons.includes('NO_MODEL_AUTHORED_SIGNATURE_SYSTEM'));});
test('deterministic completion never invents missing creative spine',()=>{const normalized=normalizeOperationalConceptProposal({name:'빈 껍데기',styleProfile:'minimal'});const validation=validateOperationalConcept(normalized);assert.equal(validation.pass,false);assert.ok(validation.missing.includes('identitySentence'));assert.ok(validation.missing.includes('coreLoop'));assert.ok(validation.missing.includes('storyHook'));assert.ok(validation.missing.includes('prototypeHypothesis'));});
test('incubator module can be imported from an input-type module where argv[1] is absent',()=>{const result=spawnSync(process.execPath,['--input-type=module','-e',"await import('./tools/autonomous-new-game-incubator.mjs'); console.log('IMPORT_OK')"],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);assert.match(result.stdout,/IMPORT_OK/);});
