import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { runRobloxAutonomousBalanceWorker } from '../tools/vibe2-roblox-autonomous-balance-worker.mjs';

function git(cwd,args){return execFileSync('git',args,{cwd,encoding:'utf8'}).trim();}
function fixture(){
  const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'vibe2-r5-balance-'));git(cwd,['init']);git(cwd,['config','user.email','qa@example.invalid']);git(cwd,['config','user.name','Vibe2 QA']);fs.writeFileSync(path.join(cwd,'README.md'),'fixture\n');git(cwd,['add','.']);git(cwd,['commit','-m','fixture']);git(cwd,['checkout','-b','vibe2/candidate/r5-balance-test']);
  const sourceRoot='roblox-games/seed-roblox-obby-party-minigam-tower-of-hell';fs.mkdirSync(path.join(cwd,sourceRoot,'server'),{recursive:true});fs.mkdirSync(path.join(cwd,sourceRoot,'client'),{recursive:true});fs.mkdirSync(path.join(cwd,'.vibe2'),{recursive:true});
  const blocks=[];for(let stage=1;stage<=12;stage+=1){const prefix=stage===1?'  if':stage===12?'  else\n    -- stage 12':'  elseif';if(stage===12){blocks.push(`${prefix}\n    addDisappearingPlatform(stageModel, stage, "A", stagePoint(previousPosition, checkpointPosition, 0.2), Vector3.new(8, 1, 7), accent, 0)`);}else if(stage===7){blocks.push(`${prefix} stage == ${stage} then\n    local arena = addPlatform(stageModel, stage, "A", stagePoint(previousPosition, checkpointPosition, 0.34), Vector3.new(18, 1, 13), dark, Enum.Material.Metal)\n    addSpinner(stageModel, stage, arena.Position + Vector3.new(0, 2.4, 0), 16, 1.45, 0)`);}else{blocks.push(`${prefix} stage == ${stage} then\n    addPlatform(stageModel, stage, "A", stagePoint(previousPosition, checkpointPosition, 0.3), Vector3.new(9, 1, 8), neutral, Enum.Material.Metal)`);}}
  const server=`local course = Instance.new("Model")\ncourse:SetAttribute("MapRevision", "R4")\nfor stage = 1, 12 do\n${blocks.join('\n')}\n  -- Preserve the original per-stage hazard naming contract while placing danger below the route.\nend\n`;fs.writeFileSync(path.join(cwd,sourceRoot,'server','Game.server.luau'),server);fs.writeFileSync(path.join(cwd,sourceRoot,'client','Game.client.luau'),'-- client unchanged\n');
  const order={run:true,workMode:'source-change-candidate',taskId:'OWNER-ROBLOX-OBBY-AUTONOMOUS-BALANCE-20260916-R5',gameId:'seed-roblox-obby-party-minigam-tower-of-hell',target:'roblox',goal:'PHASE_4_AUTONOMOUS_PLAYTEST_BALANCE',priority:'critical',releaseState:'development-confirmed',source:{root:sourceRoot,responsibleFiles:[`${sourceRoot}/server/Game.server.luau`,`${sourceRoot}/client/Game.client.luau`]},workerPolicy:{directMainWrite:false},developmentExecution:{executor:'deterministic-source-worker',recipe:'roblox-obby-autonomous-balance-v1'},exploration:{reuseKey:'qa-r5'}};fs.writeFileSync(path.join(cwd,'.vibe2','work-order-effective.json'),JSON.stringify(order,null,2));
  const stages=Array.from({length:12},(_,i)=>({stage:i+1,success:true,elapsedMs:1000,retries:0,deaths:0,stalledMs:0}));stages[6]={stage:7,success:false,elapsedMs:6500,retries:2,deaths:1,stalledMs:1800};const telemetry={version:1,authority:'vibe2-roblox-skyline-input-playtest',runtimeVerified:true,inputBased:true,inputProfile:'keyboard-default-movement',capabilities:{virtualInput:true,studioTestService:true},metrics:{inputActions:80,jumpCount:24,deaths:1,retries:2},stages};const evidenceFile=path.join(cwd,'telemetry.json');fs.writeFileSync(evidenceFile,JSON.stringify(telemetry,null,2));return{cwd,sourceRoot,evidenceFile};
}

test('R5 balance worker changes only the verified worst stage with a bounded deterministic adjustment',()=>{const f=fixture();try{const before=fs.readFileSync(path.join(f.cwd,f.sourceRoot,'server','Game.server.luau'),'utf8');const manifest=runRobloxAutonomousBalanceWorker({cwd:f.cwd,applySource:true,evidenceFile:f.evidenceFile});const after=fs.readFileSync(path.join(f.cwd,f.sourceRoot,'server','Game.server.luau'),'utf8');assert.equal(manifest.aiUsed,false);assert.equal(manifest.deterministicRecipe,'roblox-obby-autonomous-balance-v1');assert.equal(manifest.telemetryEvidence.selectedStage,7);assert.equal(manifest.telemetryEvidence.adjustment.kind,'spinner-speed');assert.match(before,/16, 1\.45, 0/);assert.match(after,/16, 1\.31, 0/);assert.match(after,/stage == 6 then[\s\S]*Vector3\.new\(9, 1, 8\)/);assert.equal(manifest.fullFileRewriteAllowed,false);assert.deepEqual(manifest.changedFiles,['server/Game.server.luau']);}finally{fs.rmSync(f.cwd,{recursive:true,force:true});}});

test('R5 balance worker refuses unverified or non-input telemetry',()=>{const f=fixture();try{const bad=JSON.parse(fs.readFileSync(f.evidenceFile,'utf8'));bad.inputBased=false;fs.writeFileSync(f.evidenceFile,JSON.stringify(bad));assert.throws(()=>runRobloxAutonomousBalanceWorker({cwd:f.cwd,applySource:true,evidenceFile:f.evidenceFile}),/verified physical-input evidence/);}finally{fs.rmSync(f.cwd,{recursive:true,force:true});}});
