import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const read=file=>fs.readFileSync(new URL('../'+file,import.meta.url),'utf8');
const json=file=>JSON.parse(read(file));

test('central machine contracts expose the verified learning closed loop',()=>{
  const roadmap=json('company-learning/platform-release-roadmap.json');
  const architecture=json('company-learning/company-architecture-map.json');
  const motor=json('company-learning/vibe2-learning-motor.json');
  const logMap=json('company-learning/company-log-map.json');
  assert.ok(Number.isInteger(roadmap.version)&&roadmap.version>=222);
  assert.ok(Number.isInteger(architecture.version)&&architecture.version>=64);
  assert.equal(motor.version,19);
  assert.equal(roadmap.learningClosedLoopContract.enabled,true);
  assert.equal(roadmap.learningClosedLoopContract.baselineAtAdoption.verifiedExperienceRecords,0);
  assert.equal(roadmap.learningClosedLoopContract.baselineAtAdoption.verifiedCodePatterns,57);
  assert.equal(roadmap.learningClosedLoopContract.productionConfidence.separateFromMasteryXp,true);
  assert.equal(roadmap.learningClosedLoopContract.strategyPromotion.thresholdsUnchanged,true);
  assert.deepEqual(roadmap.learningClosedLoopContract.commonKnowledgeLifecycle.states,['CANDIDATE','VERIFIED','PREFERRED','DEMOTED','RETIRED']);
  assert.equal(roadmap.webValidationBottleneckAdapterContract.firstPilotGameId,'fantasy-survival');
  assert.equal(architecture.learningClosedLoopTopology.externalAiRawOutputAuthority,'NONE');
  assert.equal(architecture.learningClosedLoopTopology.productionPassAuthority,'CANONICAL_QA_AND_REVIEW_ONLY');
  assert.equal(motor.closedLoop.externalAiDistilledRetrievalRequired,true);
  assert.equal(motor.closedLoop.exactInjectedKnowledgeIdTraceRequired,true);
  assert.equal(motor.closedLoop.productionConfidenceSeparateFromMastery,true);
  assert.equal(motor.mastery.domainMasteryLevelLimit,null);
  assert.equal(motor.mastery.verifiedGrowthUnbounded,true);
  assert.equal(motor.benchmarkLadder.levels,null);
  assert.equal(motor.benchmarkLadder.repeatForever,true);
  assert.equal(motor.idleTraining.practiceSignalGenerationAlwaysOn,true);
  assert.equal(motor.idleTraining.practiceGenerationLimit,null);
  assert.equal(motor.idleTraining.productionPresenceDoesNotSuppressPracticeGeneration,true);
  assert.equal(motor.presentationLearning.runtimeMotionLearning.enabled,true);
  assert.equal(motor.presentationLearning.runtimeMotionLearning.existingLearningMotorOnly,true);
  assert.equal(motor.presentationLearning.runtimeMotionLearning.separateTrainerForbidden,true);
  assert.equal(motor.presentationLearning.runtimeMotionLearning.preparedSemanticMayEnterPositiveMastery,false);
  assert.equal(motor.presentationLearning.runtimeMotionLearning.rawTelemetryMayEnterCanonicalTraining,false);
  assert.equal(motor.presentationLearning.runtimeMotionLearning.verifiedProjectOutcomeRequiredForPositiveMastery,true);
  assert.equal(motor.presentationLearning.runtimeMotionLearning.verifiedFailureMayTeachAvoidPattern,true);
  assert.equal(motor.presentationLearning.runtimeMotionLearning.trainingThresholdsUnchanged,true);
  assert.equal(roadmap.continuousLearning24hContract.status,'ACTIVE_EXECUTABLE_CONTRACT');
  assert.equal(roadmap.continuousLearning24hContract.invariants.learningSignalGenerationNeverStops,true);
  assert.equal(roadmap.continuousLearning24hContract.invariants.learningQueueAccumulationNeverStops,true);
  assert.equal(roadmap.continuousLearning24hContract.invariants.productionPresenceDoesNotSuppressLearningGeneration,true);
  assert.equal(roadmap.continuousLearning24hContract.resourcePolicy.signalGenerationAndQueueingContinueWhileYielded,true);
  assert.equal(motor.continuous24h.allLearningDomainsAlwaysActive,true);
  assert.equal(motor.continuous24h.executionLaneRunsDuringProduction,true);
  assert.equal(motor.idleTraining.productionPresenceDoesNotSuppressLearningExecution,true);
  assert.equal(motor.idleTraining.minimumConcurrentLearningLaneRequired,true);
  assert.equal(motor.presentationLearning.studioAssetUniverse.enabled,true);
  assert.equal(motor.presentationLearning.studioAssetUniverse.existingLearningMotorOnly,true);
  assert.equal(motor.presentationLearning.studioAssetUniverse.separateTrainerForbidden,true);
  assert.equal(motor.presentationLearning.studioAssetUniverse.positiveMasteryRequiresVerifiedNativeRuntimePass,true);
  assert.equal(motor.presentationLearning.studioAssetUniverse.preparedSemanticMayIncreaseMastery,false);
  assert.equal(motor.presentationLearning.studioAssetUniverse.rawCoverageOrTelemetryDirectTraining,false);
  assert.ok(motor.idleTraining.drills.includes('UNIVERSAL_ASSET_COVERAGE_DRILL'));
  assert.ok(motor.idleTraining.drills.includes('CLOTHING_ARMOR_LIBRARY_DRILL'));
  assert.ok(motor.idleTraining.drills.includes('BUILDING_MODULAR_LIBRARY_DRILL'));
  for(const domain of ['CONCEPT_DIRECTION','WORLD_GENERATION','LEVEL_DESIGN','ROUTE_DESIGN','STREAMING_OPTIMIZATION','MAIN_STORY_GENERATION','QUEST_GRAPH','FORESHADOWING_PAYOFF','TWIST_EVIDENCE_CHAIN','CHARACTER_VOICE','CHARACTER_RELATIONSHIP_MEMORY','CHARACTER_BEHAVIOR','COMPANION_BEHAVIOR','NPC_BEHAVIOR','MONSTER_BEHAVIOR_PERSONALITY','WORLD_NARRATIVE_BINDING']){
    assert.ok(motor.mastery.domains.includes(domain),domain);
  }
  assert.equal(motor.worldConceptLearning?.existingLearningMotorOnly,true);
  assert.equal(motor.worldConceptLearning?.shadowTrainerForbidden,true);
  assert.equal(motor.worldConceptLearning?.preparedSemanticMayIncreaseMastery,false);
  assert.equal(roadmap.learningClosedLoopContract?.specializedGameDevelopmentMastery?.existingCanonicalLearningMotorOnly,true);
  assert.equal(roadmap.learningClosedLoopContract?.worldAndConceptLearning?.rawReferenceImageOrProtectedLayoutCannotBecomeReusableTemplate,true);
  assert.equal(roadmap.learningClosedLoopContract?.worldAndConceptLearning?.existingGamePatternDistillation?.minimumIndependentVerifiedGames,2);
  assert.equal(roadmap.learningClosedLoopContract?.worldAndConceptLearning?.existingGamePatternDistillation?.rawCoordinatesOrExactLayoutForbidden,true);
  assert.equal(motor.worldConceptLearning?.existingGamePatternDistillation?.enabled,true);
  assert.equal(motor.worldConceptLearning?.existingGamePatternDistillation?.minimumIndependentVerifiedGamesForCrossGameReuse,2);
  assert.equal(motor.worldConceptLearning?.existingGamePatternDistillation?.directMasteryCredit,false);
  assert.equal(architecture.assetProductionParallelism?.companyGraphicsLibrary24h?.existingGameWorldPatternDistillation?.shadowTrainerForbidden,true);
  assert.equal(logMap.existingGameWorldPatternEvidenceContract?.singleGameCrossGamePromotionForbidden,true);
  assert.equal(logMap.existingGameWorldPatternEvidenceContract?.positiveCrossGameReuseRequiresTwoIndependentVerifiedGames,true);
  assert.equal(logMap.existingGameWorldPatternEvidenceContract?.exactCoordinatesTerrainMeshOrLayoutInLearningEvidenceForbidden,true);
  const ingress=roadmap.learningClosedLoopContract?.specializedGameDevelopmentMastery?.verifiedQueueEvidenceIngress;
  assert.equal(ingress?.enabled,true);
  assert.equal(ingress?.existingCanonicalLearningMotorOnly,true);
  assert.equal(ingress?.oneTaskOutcomeCreatesAtMostOnePositiveAndOneNegativeSyntheticExperience,true);
  assert.equal(ingress?.infrastructureFailureMustNotPenalizeMastery,true);
  assert.equal(motor.verifiedSpecializedQueueEvidenceIngress?.enabled,true);
  assert.equal(motor.verifiedSpecializedQueueEvidenceIngress?.existingSeenExperienceDedupeRequired,true);
  assert.equal(architecture.learningClosedLoopTopology?.specializedGameDevelopmentMastery?.verifiedQueueEvidenceIngress?.separateTrainer,false);
  assert.equal(ingress?.persistAcceptedSyntheticExperienceToCanonicalExperienceMemory,true);
  assert.equal(ingress?.canonicalExperienceStore,'.vibe2/experience.json');
  assert.equal(ingress?.sameCycleRetrievalAndHandoffUseMergedExperienceMemory,true);
  assert.equal(motor.verifiedSpecializedQueueEvidenceIngress?.persistToCanonicalExperienceMemory,true);
  assert.equal(motor.verifiedSpecializedQueueEvidenceIngress?.outcomeIdEvidenceTokenRequired,true);
  assert.equal(ingress?.nativePositiveRequiresAuthoritativeTargetEngineQa,true);
  assert.equal(ingress?.nativeTargetProofMustBeRecheckedAtCanonicalIngress,true);
  assert.equal(ingress?.uefnPositiveBlockedUntilAuthoritativeExecutorEvidenceContractExists,true);
  assert.equal(motor.verifiedSpecializedQueueEvidenceIngress?.nativeTargetProofRecheckedAtCanonicalIngress,true);
  assert.equal(motor.verifiedSpecializedQueueEvidenceIngress?.uefnPositiveBlockedUntilAuthoritativeExecutorEvidenceContractExists,true);
  assert.equal(motor.verifiedSpecializedQueueEvidenceIngress?.finalMarkerMustBeExactEvidenceToken,true);
  assert.equal(motor.verifiedSpecializedQueueEvidenceIngress?.prefixedFocusedQaTokenCannotMatchFinalMarker,true);
  assert.equal(motor.verifiedSpecializedQueueEvidenceIngress?.positiveFanInProvenanceRequired,true);
  assert.equal(motor.verifiedSpecializedQueueEvidenceIngress?.negativeVerifiedFailureProvenanceRequired,true);
  assert.equal(motor.verifiedSpecializedQueueEvidenceIngress?.negativeMarkerAloneMustNotPenalizeMastery,true);
  assert.equal(motor.verifiedSpecializedQueueEvidenceIngress?.negativeProvenanceTokens?.verification,'specialized-negative-verification:FAIL');
  const producer=ingress?.producerContract;
  assert.equal(producer?.nativeTwoStageFanInReview,true);
  assert.equal(producer?.preNativeFanInMayApproveGameCandidateButMustNotEmitNativePositiveMarkerWithoutEngineQa,true);
  assert.equal(producer?.postNativeFinalReviewImplementation,'tools/vibe2-fan-in-review.mjs');
  assert.equal(producer?.postNativeFinalReviewMustPreserveTaskStatusAndReleaseDecision,true);
  assert.equal(producer?.candidateResultWorkflowMayInvokeFanInReviewButMayNotMintVerifiedMarkerItself,true);
  assert.equal(producer?.postNativeFinalReviewRequiresExistingPreNativeRegressionAndReviewPass,true);
  assert.equal(producer?.postNativeFinalReviewRequiresFocusedQaPassTraceForEachMarker,true);
  const architectureIngress=architecture.learningClosedLoopTopology?.specializedGameDevelopmentMastery?.verifiedQueueEvidenceIngress;
  assert.equal(architectureIngress?.nativeTwoStageFanInReview,true);
  assert.equal(architectureIngress?.postNativeFinalReviewImplementation,'tools/vibe2-fan-in-review.mjs');
  assert.equal(logMap.specializedVerifiedQueueEvidenceContract?.nativeTwoStageReviewRequired,true);
  assert.equal(logMap.specializedVerifiedQueueEvidenceContract?.candidateResultWorkflowCannotMintFinalMarker,true);
  assert.equal(roadmap.roblox?.studioExecution?.enabled,true);
  assert.equal(roadmap.roblox?.studioExecution?.localPlaceFileRequired,true);
  assert.equal(roadmap.roblox?.studioExecution?.onlinePublishedPlaceDirectOpenForbidden,true);
  assert.equal(roadmap.roblox?.studioExecution?.officialStudioMcpOnly,true);
  assert.equal(roadmap.roblox?.studioExecution?.robloxPlayerAutomationForbidden,true);
  assert.equal(roadmap.roblox?.studioExecution?.undocumentedStudioCliAutomationForbidden,true);
  assert.equal(roadmap.developmentLifecycleMachine?.modelQuotaContinuity?.learningProviderIsolation?.robloxStudioAllowedFor24hLearning,true);
  assert.equal(roadmap.developmentLifecycleMachine?.modelQuotaContinuity?.learningProviderIsolation?.robloxStudioLearningScope,'STRUCTURED_VERIFIED_OFFICIAL_STUDIO_MCP_QA_FACTS_ONLY');
  assert.equal(roadmap.developmentLifecycleMachine?.modelQuotaContinuity?.learningProviderIsolation?.robloxStudioRawViewportDirectTraining,false);
  assert.equal(roadmap.developmentLifecycleMachine?.robloxStudioUsage?.learningUseForbidden,false);
  assert.ok(roadmap.developmentLifecycleMachine?.robloxStudioUsage?.forbidden?.includes('ROBLOX_PLAYER_AUTOMATION'));
  assert.equal(architecture.learningClosedLoopTopology?.robloxStudioVerifiedRuntimeIngress?.launchInput,'LOCAL_EXACT_BUILD_PLACE_FILE_ONLY');
  assert.equal(architecture.learningClosedLoopTopology?.robloxStudioVerifiedRuntimeIngress?.onlinePlaceIdLaunchForbidden,true);
  assert.equal(architecture.learningClosedLoopTopology?.robloxStudioVerifiedRuntimeIngress?.executionTransport,'OFFICIAL_STUDIO_MCP_STDIO');
  assert.equal(architecture.learningClosedLoopTopology?.robloxStudioVerifiedRuntimeIngress?.mcpOfficialBinaryFallbackWindows,'%LOCALAPPDATA%\\Roblox\\Versions\\version-*\\StudioMCP.exe');
  assert.equal(architecture.learningClosedLoopTopology?.robloxStudioVerifiedRuntimeIngress?.generatedBatchRewrite,false);
  assert.equal(architecture.learningClosedLoopTopology?.robloxStudioVerifiedRuntimeIngress?.thirdPartyBridge,false);
  assert.equal(architecture.learningClosedLoopTopology?.robloxStudioVerifiedRuntimeIngress?.runtimeAuthority,'roblox-official-studio-mcp-runtime');
  assert.equal(architecture.learningClosedLoopTopology?.robloxStudioVerifiedRuntimeIngress?.structuredQaFactsOnly,true);
  assert.equal(architecture.learningClosedLoopTopology?.robloxStudioVerifiedRuntimeIngress?.rawViewportDirectTraining,false);
  assert.equal(architecture.learningClosedLoopTopology?.robloxStudioVerifiedRuntimeIngress?.separateTrainer,false);
  assert.equal(architecture.releaseExposureLifecycle?.robloxPerpetualInternalBuildup?.actualPlayExecutor,'.github/workflows/company-development-roblox-post-runtime-qa.yml#studio-mcp-auto-play');
});

test('continuous runner loads distilled external AI and emits exact knowledge trace',()=>{
  const runner=read('tools/vibe2-continuous-runner.mjs');
  const workflow=read('.github/workflows/vibe2-continuous-core.yml');
  assert.match(runner,/externalAiDistilledInput:externalAiDistilled/);
  assert.match(runner,/\.vibe2\/external-ai-distilled-knowledge\.json/);
  assert.match(runner,/knowledgeApplicationContract/);
  assert.match(runner,/exactInjectedKnowledgeIds/);
  assert.match(workflow,/learning-knowledge-ids:/);
  assert.match(workflow,/knowledgeApplication/);
  assert.match(workflow,/version:16/);
  assert.match(workflow,/workLock/);
});

test('Web adapter stays deterministic while external AI remains in a separate verified distillation lane',()=>{
  const bootstrap=read('tools/company-development-web-bootstrap.mjs');
  const devWorkflow=read('.github/workflows/company-development-confirmed-runtime.yml');
  const webIngest=read('tools/vibe2-web-experience-ingest.mjs');
  assert.match(bootstrap,/buildWebContractAdapterPlan/);
  assert.match(bootstrap,/WEB_CONTRACT_EXTERNAL_AI_ADVISORY=DEFERRED_TO_VERIFIED_DISTILLATION_LANE/);
  assert.doesNotMatch(bootstrap,/GEMINI_API_KEY|generativelanguage\.googleapis|rawOutputSha256/);
  assert.doesNotMatch(devWorkflow,/GEMINI_API_KEY|webExternalAiLearningCandidate|externalAiCandidateFromBootstrap/);
  assert.match(webIngest,/distillExternalAiKnowledge/);
  assert.match(webIngest,/formalImplementationPassed/);
  assert.match(webIngest,/externalAiAcceptedCount/);
});

test('24H learning cycle persists verified experience and external AI distilled stores together',()=>{
  const workflow=read('.github/workflows/vibe2-24h-runner.yml');
  assert.match(workflow,/--experience=\.vibe2\/experience\.json/);
  assert.match(workflow,/--external-ai-distilled=\.vibe2\/external-ai-distilled-knowledge\.json/);
  assert.match(workflow,/git add \.vibe2\/queue\.json[\s\S]*\.vibe2\/experience\.json[\s\S]*\.vibe2\/external-ai-distilled-knowledge\.json/);
  assert.match(workflow,/VIBE2_SPECIALIZED_EXPERIENCE_PERSISTED/);
  assert.match(workflow,/VIBE2_EXTERNAL_AI_ACCEPTED/);
  assert.match(workflow,/VIBE2_LEARNING_ALWAYS_ON: 'true'/);
  assert.match(workflow,/VIBE2_LEARNING_CONCURRENT_WITH_PRODUCTION: 'true'/);
  assert.match(workflow,/learning_idle:[\s\S]*if: \$\{\{ needs\.plan\.outputs\.learning_idle_queued != '0' && needs\.plan\.outputs\.runner_pressure != 'YES' \}\}/);
  assert.doesNotMatch(workflow,/learning_idle:[\s\S]{0,250}game_primary_queued == '0'/);
  assert.match(workflow,/Dispatch next cycle unconditionally/);
});

test('human-readable roadmap mirror is not part of the learning closed-loop mutation contract',()=>{
  const roadmap=json('company-learning/platform-release-roadmap.json');
  assert.equal(roadmap.learningClosedLoopContract.existingWaveSchedulerOnly,true);
  assert.equal(roadmap.learningClosedLoopContract.authorityExpansion,false);
  assert.equal(roadmap.learningClosedLoopContract.gateWeakening,false);
});
