// 파일명: qa/vibe2-weight-learning.test.mjs
import test from 'node:test';
import assert from 'node:assert/strict';
import { buildDataset, classifyFailure, computeLearningMetrics, detectContamination, evaluateAdapter, isVerifiedPass, qualityScore, routeAdapter, shouldAbortTraining } from '../tools/vibe2-weight-learning.mjs';

function verified(overrides = {}) { return { instruction: '버그를 수정해', input: '재현 조건', output: '검증된 수정 결과', sourceCommit: 'abc123', independentQa: 'PASS', browserQa: 'PASS', quality: { codeQuality: 1, noRegression: true, playImprovement: 1, ruleCompliance: 1 }, ...overrides }; }
function rows(count = 20) { return Array.from({ length: count }, (_, index) => ({ record: verified({ sourceCommit: `c${index}`, instruction: `작업 ${index}`, input: `입력 ${index}`, output: `고유 결과 ${index}` }), sourceFile: 'fixture.jsonl', index })); }

test('검증 PASS 두 종류를 모두 만족해야 학습 가능하다', () => { assert.equal(isVerifiedPass(verified()), true); assert.equal(isVerifiedPass(verified({ browserQa: 'FAIL' })), false); });
test('품질 점수와 lifecycle이 학습 데이터 승격을 막는다', () => { const data = buildDataset([...rows(20), { record: verified({ sourceCommit: 'low', instruction: '낮은 품질', quality: { codeQuality: 0, noRegression: false, playImprovement: 0, ruleCompliance: 0 } }), sourceFile: 'fixture.jsonl', index: 20 }, { record: verified({ sourceCommit: 'old', instruction: '폐기 규칙', lifecycle: 'obsolete' }), sourceFile: 'fixture.jsonl', index: 21 }], { seed: 42, evalRatio: 0.2, holdoutRatio: 0.2, minTrainSamples: 1 }); assert.equal(qualityScore(verified()), 1); assert.equal(data.stats.skippedQuality, 1); assert.equal(data.stats.skippedLifecycle, 1); assert.equal(data.stats.deprecatedUsed, false); assert.ok(data.train.length && data.eval.length && data.holdout.length); });
test('train/eval/holdout은 근접 중복 오염을 검출한다', () => { const sample = { sampleId: 'a', contentHash: 'same', instruction: 'A', input: '', output: 'B' }; const result = detectContamination({ train: [sample], eval: [{ ...sample, sampleId: 'b' }], holdout: [] }); assert.equal(result.pass, false); });
test('합성 데이터만 있는 self-training을 차단한다', () => { const synthetic = rows(24).map((item) => ({ ...item, record: { ...item.record, sourceKind: 'teacher', teacher: true } })); const data = buildDataset(synthetic, { seed: 7, evalRatio: 0.2, holdoutRatio: 0.2, minTrainSamples: 1, syntheticRatioCap: 0.5 }); assert.equal(data.train.length, 0); assert.equal(data.readyForTraining, false); });
test('adapter router는 신뢰도가 낮으면 baseline으로 fallback한다', () => { const weak = routeAdapter({ goal: '조금 개선' }, { general: { status: 'REJECTED', path: 'x' } }); assert.equal(weak.fallback, true); assert.equal(weak.adapter, null); const strong = routeAdapter({ taskType: 'unity', goal: 'Unity Android build fix' }, { unity: { status: 'PROMOTED', path: 'adapters/unity-v2' } }); assert.equal(strong.taskType, 'unity'); assert.equal(strong.adapter, 'adapters/unity-v2'); });
test('실패 taxonomy는 주요 재발 유형을 고정한다', () => { assert.equal(classifyFailure('Gradle build failed'), 'BUILD'); assert.equal(classifyFailure('localStorage save broken'), 'SAVE'); assert.equal(classifyFailure('mobile UI overflow'), 'UI'); });
test('학습 성능 지표에 효율과 재시도도 포함한다', () => { const metrics = computeLearningMetrics([{ success: true, firstAttemptQaPass: true, sameErrorRecurred: false, fixIterations: 0, ruleCompliant: true, runtimeMs: 100, memoryMb: 100, retries: 0 }, { success: false, firstAttemptQaPass: false, sameErrorRecurred: true, fixIterations: 2, ruleCompliant: false, runtimeMs: 300, memoryMb: 200, retries: 2 }]); assert.equal(metrics.successRate, 0.5); assert.equal(metrics.averageRuntimeMs, 200); assert.equal(metrics.averageRetries, 1); });
test('adapter는 무회귀, 효율, canary를 모두 만족해야 승격한다', () => { const baseline = { successRate: 0.7, firstAttemptQaPassRate: 0.6, repeatedErrorRecurrenceRate: 0.2, averageFixIterations: 1.2, ruleComplianceRate: 0.8, averageRetries: 1, averageRuntimeMs: 100, averageMemoryMb: 100 }; const candidate = { successRate: 0.8, firstAttemptQaPassRate: 0.7, repeatedErrorRecurrenceRate: 0.1, averageFixIterations: 1, ruleComplianceRate: 0.9, averageRetries: 0.8, averageRuntimeMs: 110, averageMemoryMb: 110 }; assert.equal(evaluateAdapter(baseline, candidate, { canary: { samples: 10, minimumSamples: 10, regressions: 0, ruleCompliance: true } }).verdict, 'PROMOTE'); assert.equal(evaluateAdapter(baseline, { ...candidate, averageRuntimeMs: 200 }).verdict, 'REJECT'); });
test('학습 이상 신호는 중단과 rollback을 요구한다', () => { const result = shouldAbortTraining({ lossRatio: 2.5, evalDelta: -0.1, oom: true }); assert.equal(result.abort, true); assert.equal(result.rollback, true); assert.ok(result.reasons.includes('OOM')); });
