// 파일명: qa/vibe-v2-e2e.mjs
// 역할: Vibe Maker V2 전체 실행 루프의 후보검증·권위 런타임 증거·복구·롤백 경계를 검사
import assert from 'node:assert/strict';
import {createVibeSourceRevision,createVibeV2Execution,createVibeWorkbenchCandidate,verifyVibeWorkbenchAppliedSources,createVibeGitCommitAttestation,createVibeRuntimeEvidence,createVibeGitHubWorkflowObservation,createVibeGitHubQAEvidence,mergeVibeRuntimeAndQAEvidence,advanceVibeV2Candidate,verifyVibeV2Runtime,verifyVibeV2Repair} from '../assets/vibe-v2-runtime.js';
import {replayVibeWorld} from '../assets/vibe-quality-intelligence.js';
const initial={worldId:'e2e',seed:'fixed',state:{hero:{hp:100},world:{progress:1}}},events=[{op:'set',path:'hero.status',value:'ready',timestamp:1}],baseline=replayVibeWorld({initialState:initial,events}),invariants={requiredPaths:['hero.hp'],nonNegativePaths:['hero.hp']};
const blocked=createVibeV2Execution({request:'오류 복구'});assert.equal(blocked.readyForCandidate,false);assert.ok(blocked.blockedReasons.includes('exact-revision-required'));assert.ok(blocked.blockedReasons.includes('checkpoint-required'));assert.ok(blocked.blockedReasons.includes('responsible-source-unproven'));
const execution=createVibeV2Execution({request:'오류 복구',target:'godot',revision:'rev-1',checkpointId:'cp-1',responsibleFiles:['main.gd']}),candidate=advanceVibeV2Candidate(execution,{candidate:{patch:{ui:{layout:'mobile'}}}});assert.equal(candidate.phase,'candidate-verified');assert.equal(candidate.mayRun,true);
const legacy=verifyVibeV2Runtime(candidate,{baseline,candidateWorld:baseline,invariants,candidateApplied:true,runtimeObserved:true,qaPassed:true,regressionPassed:true,exactRevision:true});assert.equal(legacy.phase,'repair-required');assert.equal(legacy.mayCommit,false);assert.ok(legacy.evidenceGate.blockedReasons.includes('candidate-not-applied'));assert.ok(legacy.evidenceGate.blockedReasons.includes('runtime-not-observed'));
const before='extends Node',after='extends Node\n# mobile ui',workbench=createVibeWorkbenchCandidate({request:'UI 수정',target:'godot',checkpointId:'workspace:physical-1',changes:[{path:'main.gd',current:before,next:after,changed:true}]});assert.equal(workbench.mayApply,true);assert.equal(workbench.execution.revision,createVibeSourceRevision([{path:'main.gd',current:after}]));assert.notEqual(workbench.execution.revision,createVibeSourceRevision([{path:'main.gd',current:before}]));const sourceEvidence=verifyVibeWorkbenchAppliedSources(workbench,{observedFiles:[{path:'main.gd',actual:after}]});assert.equal(sourceEvidence.sourceExact,true);assert.equal(sourceEvidence.checkpointId,'workspace:physical-1');
const evidence=createVibeRuntimeEvidence(workbench.execution,{sourceEvidence,runner:'deterministic-vibe-runner',revision:workbench.execution.revision,runtimeObserved:true,baseline,candidateWorld:baseline,invariants,qaPassed:true,regressionPassed:true});assert.equal(evidence.authority,'v2-runtime-evidence');assert.equal(evidence.candidateApplied,true);assert.equal(evidence.runtimeObserved,true);assert.equal(evidence.qaPassed,true);assert.equal(evidence.regressionPassed,true);assert.equal(evidence.exactRevision,true);const verified=verifyVibeV2Runtime(workbench.execution,{evidence});assert.equal(verified.phase,'verified');assert.equal(verified.mayCommit,true);assert.equal(verified.rollbackRequired,false);assert.equal(verified.evidenceGate.aiMayDeclareComplete,false);
// 브라우저 runtime과 GitHub QA는 분리한다. exact commit source attestation 없이는 workflow success도 완료 권한이 없다.
const runtimeOnly=createVibeRuntimeEvidence(workbench.execution,{sourceEvidence,runner:'deterministic-vibe-runner',revision:workbench.execution.revision,runtimeObserved:true,baseline,candidateWorld:baseline,invariants,qaPassed:false,regressionPassed:false}),head='0123456789abcdef0123456789abcdef01234567',workflowObservation=createVibeGitHubWorkflowObservation({workflowHeadSha:head,runs:[{id:11,name:'Vibe QA',head_sha:head,status:'completed',conclusion:'success',event:'push'},{id:12,name:'Vibe Integrated Regression',head_sha:head,status:'completed',conclusion:'success',event:'push'}]});assert.equal(workflowObservation.verified,true);
const noAttestationQA=createVibeGitHubQAEvidence(workbench.execution,{sourceEvidence,artifactSourceRevision:workbench.execution.revision,workflowHeadSha:head,qaPassed:true,regressionPassed:true,workflowObservation});assert.equal(noAttestationQA.commitAttested,false);assert.equal(noAttestationQA.qaPassed,false);assert.equal(verifyVibeV2Runtime(workbench.execution,{evidence:mergeVibeRuntimeAndQAEvidence(workbench.execution,{runtimeEvidence:runtimeOnly,qaEvidence:noAttestationQA})}).mayCommit,false);
const gitAttestation=createVibeGitCommitAttestation(workbench.execution,{sourceEvidence,commitSha:head,committedFiles:[{path:'main.gd',source:after}]});assert.equal(gitAttestation.verified,true);assert.equal(gitAttestation.commitSha,head);assert.equal(gitAttestation.revisionExact,true);const wrongCommitAttestation=createVibeGitCommitAttestation(workbench.execution,{sourceEvidence,commitSha:head,committedFiles:[{path:'main.gd',source:before}]});assert.equal(wrongCommitAttestation.verified,false);assert.equal(wrongCommitAttestation.revisionExact,false);
const githubQA=createVibeGitHubQAEvidence(workbench.execution,{sourceEvidence,gitAttestation,artifactSourceRevision:workbench.execution.revision,workflowHeadSha:head,qaPassed:true,regressionPassed:true,workflowObservation}),merged=mergeVibeRuntimeAndQAEvidence(workbench.execution,{runtimeEvidence:runtimeOnly,qaEvidence:githubQA});assert.equal(githubQA.commitAttested,true);assert.equal(githubQA.workflowObserved,true);assert.equal(githubQA.qaPassed,true);assert.equal(merged.runtimeObserved,true);assert.equal(merged.qaPassed,true);assert.equal(merged.regressionPassed,true);assert.equal(verifyVibeV2Runtime(workbench.execution,{evidence:merged}).mayCommit,true);
const otherHead='ffffffffffffffffffffffffffffffffffffffff',wrongHeadQA=createVibeGitHubQAEvidence(workbench.execution,{sourceEvidence,gitAttestation,artifactSourceRevision:workbench.execution.revision,workflowHeadSha:otherHead,qaPassed:true,regressionPassed:true,workflowObservation});assert.equal(wrongHeadQA.commitAttested,false);assert.equal(wrongHeadQA.qaPassed,false);const incompleteObservation=createVibeGitHubWorkflowObservation({workflowHeadSha:head,runs:[{id:13,name:'Vibe QA',head_sha:head,status:'completed',conclusion:'success'}]});assert.equal(incompleteObservation.verified,false);
const stale=createVibeRuntimeEvidence(workbench.execution,{sourceEvidence,runner:'deterministic-vibe-runner',revision:'stale',runtimeObserved:true,baseline,candidateWorld:baseline,invariants,qaPassed:true,regressionPassed:true});assert.equal(stale.exactRevision,false);assert.equal(stale.runtimeObserved,false);assert.equal(verifyVibeV2Runtime(workbench.execution,{evidence:stale}).mayCommit,false);const fake=createVibeRuntimeEvidence(workbench.execution,{sourceEvidence,runner:'ui-manual-toggle',revision:workbench.execution.revision,runtimeObserved:true,baseline,candidateWorld:baseline,invariants,qaPassed:true,regressionPassed:true});assert.equal(fake.runtimeObserved,false);assert.equal(fake.qaPassed,false);assert.equal(verifyVibeV2Runtime(workbench.execution,{evidence:fake}).mayCommit,false);
const divergent=replayVibeWorld({initialState:initial,events:[...events,{op:'add',path:'hero.hp',value:-150,timestamp:2}]}),badEvidence=createVibeRuntimeEvidence(workbench.execution,{sourceEvidence,runner:'deterministic-vibe-runner',revision:workbench.execution.revision,runtimeObserved:true,baseline,candidateWorld:divergent,invariants,qaPassed:true,regressionPassed:true}),repairRequired=verifyVibeV2Runtime(workbench.execution,{evidence:badEvidence});assert.equal(repairRequired.phase,'repair-required');assert.equal(repairRequired.mayCommit,false);assert.equal(repairRequired.rollbackRequired,true);assert.equal(repairRequired.repairPlan.autoApplyAllowed,false);const rollback=verifyVibeV2Repair(repairRequired,{before:baseline,after:baseline,invariants,qaPassed:true,exactRevision:false});assert.equal(rollback.phase,'rollback');const repaired=verifyVibeV2Repair(repairRequired,{before:baseline,after:baseline,invariants,qaPassed:true,exactRevision:true});assert.equal(repaired.phase,'verified');assert.equal(repaired.mayCommit,true);
const protectedCandidate=advanceVibeV2Candidate(execution,{candidate:{patch:{combat:{damage:999}}}});assert.equal(protectedCandidate.phase,'candidate-rejected');assert.equal(protectedCandidate.mayRun,false);assert.ok(protectedCandidate.candidateValidation.touched.includes('damage'));
console.log('vibe-v2-e2e: exact git commit attestation required');