import assert from 'node:assert/strict';
import fs from 'node:fs';
import { buildVibeVerifiedMemoryIndex, retrieveVibeVerifiedPatterns, createVibeTaskPlaybook, createVibePumpModeContract } from '../assets/vibe-v3-engine.js';
import { createVibePumpCandidatePlan } from '../assets/vibe-development-ai.js';
import { buildPumpArtifacts } from '../tools/vibe3-pump-index.mjs';

const ordinary={sampleId:'s-code',instruction:'fix inventory save bug',output:'verified patch',taskType:'bugfix',lifecycle:'active',project:'game-a',sourceRevision:'abc1234',provenance:{sourceKind:'vibe2',sourceRevision:'abc1234'},qa:{independentQa:'PASS',browserQa:'PASS',runtime:'PASS'}};
const unity={sampleId:'s-unity',instruction:'fix Android build',output:'verified unity patch',taskType:'unity',lifecycle:'active',project:'game-b',sourceRevision:'def5678',provenance:{sourceKind:'vibe2',sourceRevision:'def5678'},qa:{independentQa:'PASS',browserQa:'NOT_APPLICABLE',runtime:'PASS'}};
const roblox={sampleId:'s-roblox',instruction:'fix Roblox save and rejoin',output:'verified roblox patch',taskType:'roblox',lifecycle:'active',project:'game-r',sourceRevision:'abc9876',provenance:{sourceKind:'vibe2',sourceRevision:'abc9876'},qa:{independentQa:'PASS',browserQa:'NOT_APPLICABLE',runtime:'PASS'}};
const webPortable={sampleId:'s-web-portable',instruction:'verified webgame touch input mobile ui save load resume performance responsive regression core loop',output:'verified web companion patch',taskType:'qa',lifecycle:'active',project:'web-game',sourceRevision:'fedcba9',sourcePaths:['web-games/web-game/index.html'],tags:['webgame','touch-input','mobile-ui','save-load','performance','responsive','regression','core-loop'],provenance:{sourceKind:'vibe3-trajectory',sourceRevision:'fedcba9',portableContextMayCrossPlatforms:true,platformPassEvidenceTransferAllowed:false},qa:{independentQa:'PASS',browserQa:'PASS',runtime:'PASS'}};
const external={sampleId:'s-blackbox',instruction:'verify black box input',output:'bounded observation',taskType:'qa',lifecycle:'active',project:'block-blast',sourceRevision:'sha256:abc',provenance:{sourceKind:'external-black-box',sourceRevision:'sha256:abc'},qa:{independentQa:'BLACK_BOX_EVIDENCE_PASS',browserQa:'NOT_APPLICABLE',runtime:'PASS'}};
const authorized={sampleId:'s-authorized',candidateId:'s-authorized',instruction:'authorized source study',input:JSON.stringify({learningDomains:['board-grid-placement','input-drag-touch'],counts:{sourceDocuments:10,assets:5}}),output:'- AUTHORIZED_SOURCE:board-grid-placement\n- AUTHORIZED_SOURCE:input-drag-touch',taskType:'coding',lifecycle:'active',project:'authorized-game',gameId:'authorized-game',sourceRevision:'sha256:auth',sourceKind:'authorized-source',provenance:{sourceKind:'authorized-source',sourceRevision:'sha256:auth',authority:'OWNER_ASSERTED_REUSE_REINTERPRETATION'},verification:{independentQa:'AUTHORIZED_SOURCE_EVIDENCE_PASS',browserQa:'NOT_APPLICABLE',runtime:'STATIC_VERIFIED',authorizedSourceEvidence:'PASS',runtimePassClaimed:false}};
const commercial={sampleId:'s-commercial',instruction:'commercial runtime reference',output:'runtime architecture lesson',taskType:'unity',lifecycle:'active',project:'commercial-game',gameId:'commercial-game',sourceRevision:'commercial-run-1',sourceKind:'commercial-runtime-reference',practiceOnly:true,runtimePromotionAllowed:false,topic:'commercial-puzzle-runtime-architecture',provenance:{sourceKind:'commercial-runtime-reference',sourceRevision:'commercial-run-1',observationKind:'BLACK_BOX_RUNTIME_ONLY',codeExtracted:false,binaryRedistributed:false},qa:{runtime:'PASS',independentQa:'NOT_APPLICABLE',browserQa:'NOT_APPLICABLE'}};
const unverified={sampleId:'bad',instruction:'guess',output:'bad',taskType:'coding',lifecycle:'active',project:'x',sourceRevision:'z',provenance:{sourceKind:'vibe2',sourceRevision:'z'},qa:{independentQa:'PASS',browserQa:'FAIL',runtime:'PASS'}};
const trajectory={trajectoryId:'traj-ok',request:'repair inventory save runtime',outcome:'VERIFIED_WINNER',metadata:{taskType:'bugfix',project:'game-a',sourceRevision:'fff1111'},finalEvidence:{runtimePass:true,qaPassed:true,regressionPassed:true,exactRevision:true,protectedStatePreserved:true,sourceRevision:'fff1111'},candidates:[{id:'c1',eligible:false,failure:'runtime crash'},{id:'c2',eligible:true,score:.9}],observableCodingTrace:{version:1,boundary:'OBSERVABLE_ACTIONS_AND_EVIDENCE_ONLY',goal:'repair inventory save runtime',capabilityDomains:['FAILURE_RECOVERY','QA_DESIGN'],steps:[{stage:'REPAIR_ATTEMPT',action:'APPLY_EVIDENCE_GUIDED_REPAIR',outcome:'FAIL',failureClass:'RUNTIME',capabilityDomain:'FAILURE_RECOVERY'},{stage:'FINAL_VERIFICATION',action:'VERIFY_SELECTED_CANDIDATE',outcome:'VERIFIED_WINNER',capabilityDomain:'QA_DESIGN'}],hiddenReasoningPersisted:false,positivePromotionAuthority:false,authority:'observable-coding-trace-only'}};

const index=buildVibeVerifiedMemoryIndex({trainingSamples:[ordinary,unity,roblox,webPortable,external,unverified],trajectories:[trajectory]});
assert.equal(index.positive.length,6);
assert(!index.positive.some(x=>x.id==='bad'));
assert(index.positive.some(x=>x.id==='s-roblox'));
assert(index.positive.some(x=>x.id==='s-web-portable'&&x.taskType==='qa'));
assert(index.failureWarnings.some(x=>x.id==='c1'));
assert(index.failureWarnings.every(x=>x.positiveTrainingAllowed===false));
const retrieval=retrieveVibeVerifiedPatterns({index,request:'inventory save bug repair',taskType:'bugfix',project:'game-a'});
assert(retrieval.successes.length>0);
assert.equal(retrieval.successes[0].entry.taskType,'bugfix');
const playbook=createVibeTaskPlaybook({taskType:'bugfix',retrieval});
assert(playbook.checklist.includes('reproduce-or-bind-failure-evidence'));
assert(playbook.reuse.length>0);
const robloxRetrieval=retrieveVibeVerifiedPatterns({index,request:'Roblox save rejoin release webgame touch mobile responsive regression core loop',taskType:'roblox',project:'game-r'});
assert(robloxRetrieval.successes.some(item=>item.entry.id==='s-web-portable'));
const robloxPlaybook=createVibeTaskPlaybook({taskType:'roblox',retrieval:robloxRetrieval});
assert.equal(robloxPlaybook.taskType,'roblox');
assert(robloxPlaybook.checklist.includes('separate-server-client-authority'));
assert(robloxPlaybook.checklist.includes('publish-only-after-exact-revision-pass'));

const pump=createVibePumpModeContract();
assert.equal(pump.enabled,true);
assert.equal(pump.candidateTournament.default,5);
assert.equal(pump.candidateTournament.min,3);
assert.equal(pump.candidateTournament.max,5);
assert.equal(pump.repairLoop.maxAttempts,3);
assert.equal(pump.experiencePump.benchmarkCountsAsTrainingSample,false);
assert.equal(pump.weights.localWeightsRequiredForPump,false);
assert.equal(pump.weights.githubHostedModelTrainingAllowed,false);

const candidatePlan=createVibePumpCandidatePlan({environment:'chatgpt',candidateCount:5,teacherCandidateMax:2,groq:{available:true},mistral:{available:true}});
assert.equal(candidatePlan.candidateCount,5);
assert.equal(candidatePlan.teachers.length,2);
assert(candidatePlan.teachers.every(x=>x.authoritative===false&&x.completionAuthority===false));
assert.equal(candidatePlan.paidFallback,false);

const artifacts=buildPumpArtifacts({trainingSamples:[ordinary,unity,roblox,webPortable,external,authorized,commercial,unverified],trajectories:[trajectory]});
assert.equal(Object.keys(artifacts.playbooks.taskTypes).length,8);
assert.equal(artifacts.playbooks.taskTypes.roblox.taskType,'roblox');
assert(artifacts.playbooks.taskTypes.roblox.reuse.some(item=>item.id==='s-web-portable'));
assert.equal(artifacts.playbooks.policy.portableWebContextForRoblox,true);
assert.equal(artifacts.playbooks.policy.platformEvidenceTransferAllowed,false);
assert(artifacts.benchmark.cases.length>0);
assert(artifacts.benchmark.cases.every(x=>x.countsAsTrainingSample===false));
assert(artifacts.benchmark.cases.every(x=>x.candidateCount===5&&x.maxRepairAttempts===3));
assert.equal(artifacts.recombination.policy.copyMode,false);
assert.equal(artifacts.recombination.policy.transformativeReinterpretation,true);
assert(artifacts.recombination.materials.some(x=>x.id==='s-authorized'&&x.capabilities.assetStructure===true));
assert(artifacts.recombination.materials.some(x=>x.id==='s-commercial'&&x.evidenceMode==='BLACK_BOX_RUNTIME'));
assert(artifacts.recombination.recipes.length>0);
assert(artifacts.recombination.recipes.every(x=>new Set(x.sourceProjects).size>=2));
assert(artifacts.recombination.recipes.every(x=>x.assetStrategy.newAssetRequired===true&&x.assetStrategy.rawPixelReuseAllowed===false));
assert(artifacts.recombination.recipes.every(x=>x.codeStrategy.newImplementationRequired===true&&x.codeStrategy.verbatimSourceReuseAllowed===false));
assert.equal(artifacts.playbooks.transformativeRecombination.enabled,true);
assert.equal(artifacts.playbooks.transformativeRecombination.rawSourceOutputAllowed,false);
assert.equal(artifacts.capabilityDistillation.verifiedTraceCount,1);
assert.equal(artifacts.capabilityDistillation.patternCount,2);
assert.equal(artifacts.capabilityDistillation.policy.hiddenReasoningPersisted,false);
assert.equal(artifacts.capabilityDistillation.policy.automaticPromotionAllowed,false);
assert.equal(artifacts.playbooks.capabilityDistillation.authority,'capability-distillation-retrieval-context-only');
assert(artifacts.playbooks.capabilityDistillation.patterns.some(item=>item.domain==='FAILURE_RECOVERY'&&item.state==='OBSERVED_VERIFIED'));
assert(artifacts.playbooks.capabilityDistillation.patterns.every(item=>item.directPromotionAllowed===false&&item.rawPatchReuseAllowed===false));

const ingestWorkflow=fs.readFileSync('.github/workflows/vibe2-distillation-ingest.yml','utf8');
const localTrainingWorkflow=fs.readFileSync('.github/workflows/vibe2-local-distillation-train.yml','utf8');
assert.match(ingestWorkflow,/VIBE2_LEARNING_RUNTIME_BRANCH:\s*vibe2-learning-runtime/);
assert.match(ingestWorkflow,/git push --force-with-lease=/);
assert(!ingestWorkflow.includes('gh pr create'));
assert((localTrainingWorkflow.match(/ref:\s*vibe2-learning-runtime/g)||[]).length>=2);
console.log('PASS Vibe3 Pump verified RAG including Web portable context without Roblox evidence transfer');
