local Style={
  Lighting={Brightness=2.0,ClockTime=17.3,Ambient=Color3.fromRGB(95,92,116),OutdoorAmbient=Color3.fromRGB(112,106,132)},
  Ground=Color3.fromRGB(86,94,82),
  Stone=Color3.fromRGB(94,91,101),
  Crystal=Color3.fromRGB(125,96,255),
  Gold=Color3.fromRGB(239,191,86),
  Enemy=Color3.fromRGB(158,69,73),
  Boss=Color3.fromRGB(73,35,94),
  CompanionColors={
    KYLE=Color3.fromRGB(190,96,65),
    SERA=Color3.fromRGB(75,104,128),
    IRIS=Color3.fromRGB(130,89,196),
  }
}
return table.freeze(Style)
